### PR TITLE
Character - Separate first name and surname

### LINKED ISSUE #6107: Search and Rescue - Issue with name generation
The issue is maybe rather in Character name generation but the Search and Rescue module shows them off well. The name is generated as one string which means you can't directly access the given name/surname after generation. This leads to methods like **splitName()** below for the cases where you want a character and use the surname for something, like in the case below, as a company name.

https://github.com/pioneerspacesim/pioneer/blob/dd7d40dfc29c15a09647798913b59fdbf2fa570e/data/modules/SearchRescue/SearchRescue.lua#L284-L290

In the case of **splitName()** above we see two problems:
1 - It doesn't handle more than one given names well. It assumes just two name components in total so the second given name is listed as surname.
2 - You don't seem to be able to access the substitute characters in the culture files as the logic breaks down when names have non ASCII signs in them.

It looks like the name should best be generated as a list where the given names and the surname/s are kept separate. Then you could have a **Character.surname** method to access the surname.

### Observed behaviour

In the examples below a family company is in trouble and the client presents themselves with full name followed by the company name. The clients surname is then reused as a component in the company name. As we see this doesn't always work.

**Examples of oddities with non ascii signs**

Image

Image

Image

**Example of name with more than two components**

Image

### Steps to reproduce

Generate a lot of Search and Rescue missions and read the mission intros. There aren't that many double surnames in the game so I manually edited a culture file with only multiple surnames and/or non ASCII signs.

__My pioneer version (and OS):__
master: dd7d40dfc29c15a09647798913b59fdbf2fa570e as of April 4, 2025

### PR DESCRIPTION
**Pull request by zonkmachine**
Generate first name and surname separately.

We need to access the names separately but they were previously generated together and saved as one in **Character.name**, with the result of having to go through the hoops of separating the names which is really hard if the name is composed of more than two names.
    
Now they are generated as two separate strings, **Character.firstname** and **Character.surname**. **Character.name** is still present. **Culture.Names()** / **NameGen.Names()** is introduced to generate a full name as two separate strings.

Example NameGen
```
name1, name2 = NameGen.Names()
```

Example Character
```
someperson = Character.New()
print("Hi " .. someperson.firstname)
```

The issue in Search and Rescue is fixed and also, the Assassination module gets a touch-up. No translated strings touched.

Supersedes #6112
Fixes #6107

### CODE REVIEW

File: data/modules/Assassination/Assassination.lua [hunk 1]
```diff
@@ -99,8 +99,8 @@ local onChat = function (form, ref, option)
 		local sbody = ad.location:GetSystemBody()
 
 		form:SetMessage(string.interp(l.X_WILL_BE_LEAVING, {
-		  target    = ad.target,
-		  spaceport = sbody.name,
+		  target    = true and ad.targetsurname or ad.target,	-- If targetsurname is missing, then older version.
```
Comment (sturnclaw) [inline data/modules/Assassination/Assassination.lua:102]: Note that you do not need a trinary expression here - `ad.targetsurname or ad.target` would suffice.

**Review by sturnclaw — APPROVED** [review]
Looks good to me!

**Comment by impaktor** [comment]
Is there some filter somewhere that makes all names ascii compatible? Or this is not needed?

Just thinking if someone is searching "Örjan's system" in star chart, and not endowed with umlaut keyboard. 

(I've forgotten the exact code path how this stuff works, but that's the one thought I had).

**Comment by zonkmachine** [comment]
> Is there some filter somewhere that makes all names ascii compatible? Or this is not needed?

No. It looks like the ascii filter is only used in body naming. If I flip that test off and change body names to FirstName the body names will show non-ascii signs just well. Not needed unless we want **Emma V** and **Bob** to turn up. The motivation for only ascii signs in body names is given in the code as just _"-- want only ascii compatible characers in name"_, they still work though. Also, first names used to name places isn't uncommon. I can look into an ascii test for first names too.

> Just thinking if someone is searching "Örjan's system" i

Are the culture names used in system names at all? I've only seen them on planets, asteroids and settlements/stations.

File: data/modules/Assassination/Assassination.lua (hunk 1 above)
Comment (zonkmachine) [reply data/modules/Assassination/Assassination.lua]: Fixed!

**Comment by zonkmachine** [comment]
FYI! I haven't tested the documentation as NaturalDocs wouldn't work for me for some reason. I won't have time to look into that.

**Comment by zonkmachine** [comment]
Last fix to capitalize surnames when used as company names "de Jong" becomes "De Jong". Not heavily into grammar here but that seems to be the way it's done.

File: data/libs/NameGen.lua [hunk 2]
```diff
@@ -56,6 +56,79 @@ NameGen = {
...
+--
+--
+-- Availability:
+--
+--   2025
+--
+-- Status:
+--
+--   experimental
+--
```
Comment (impaktor) [inline data/libs/NameGen.lua:90]: You don't need to remove or edit anything, but I think robn said - way back - that the "availability" and "experimental" tags are deprecated, as they don't really serve any function, I think, but I'm not willing to swear by it.

File: data/modules/Assassination/Assassination.lua [hunk 3]
```diff
@@ -99,8 +99,8 @@ local onChat = function (form, ref, option)
 		local sbody = ad.location:GetSystemBody()
 
 		form:SetMessage(string.interp(l.X_WILL_BE_LEAVING, {
-		  target    = ad.target,
-		  spaceport = sbody.name,
+		  target    = ad.targetsurname or ad.target,	-- If targetsurname is missing, then older version.
+		  spaceport = sbody.name,						-- Instead hand over previously used full name + title.
```
Comment (impaktor) [inline data/modules/Assassination/Assassination.lua:103]: Is that comment indented with space or tabs? github editor gives me the impression it's tabs?

**Review by impaktor — APPROVED** [review]
I've not tested it, but I assume it's been self-tested/reviewed
I suggest merge after the zuper-ztable release is out.

Also, I note an asymetry in using "first name" & "surname" vs. "first and last name", in documentation (and variables?). I dunno which is best, I'm just pointing it out.

File: data/libs/NameGen.lua (hunk 2 above)
Comment (zonkmachine) [reply data/libs/NameGen.lua:90]: Then I'll probably remove it. It's unnecessary noise.

**Comment by zonkmachine** [comment]
> I've not tested it, but I assume it's been self-tested/reviewed I suggest merge after the zuper-ztable release is out.

:+1: I've tested it extensively. Both Assassination and Search and Rescue upgrades by opening up already created missions as they were earlier and newer missions as corrected. Works fine.

> Also, I note an asymetry in using "first name" & "surname" vs. "first and last name", in documentation (and variables?). I dunno which is best, I'm just pointing it out.

`grep -R [lL]ast[nN]ame data/` 

shows that it's only **Search and Rescue** and some of the culture files that use lastname. I didn't change it from it's earlier form but it's probably a good idea to go surname at least in that file.

File: data/modules/Assassination/Assassination.lua (hunk 3 above)
Comment (zonkmachine) [reply data/modules/Assassination/Assassination.lua]: Fixed!

File: data/libs/NameGen.lua (hunk 2 above)
Comment (zonkmachine) [reply data/libs/NameGen.lua]: Fixed!

**Comment by zonkmachine** [comment]
https://github.com/pioneerspacesim/pioneer/labels/Savegame%20bump

I don't mind the label but the PR shouldn't break ongoing games.

**Comment by sturnclaw** [comment]
Right then - I'll merge this for the upcoming hotfix. I don't think full names are used in system generation, so there should be no impact on breaking saves in that regard.
