### PR TITLE
Avoid misaligned read when loading SGM files

### LINKED ISSUE #5687: scenegraph/Serializer.h: load of misaligned address
### Observed behaviour

[UndefinedBehaviorSanitizer](https://gcc.gnu.org/onlinedocs/gcc/Instrumentation-Options.html#index-fsanitize_003dundefined) complains about "load of misaligned address" during game starttup. I see about a dozen messages like below.

```
/home/cdda/git/pioneer/src/scenegraph/Serializer.h:152:8: runtime error: load of misaligned address 0x7f768187841d for type 'const float', which requires 4 byte alignment
0x7f768187841d: note: pointer points here
 00 00 00 01 00 00 00  00 d4 bb 4b b5 00 00 80  3f 20 0e 04 c1 6f ea 9d  3e 26 ea af 41 0f 00 00  00
             ^ 
    #0 0x10d6257 in void Serializer::Reader::readObject<float>(float&) /home/cdda/git/pioneer/src/scenegraph/Serializer.h:152
    #1 0x10d6257 in Serializer::Reader& Serializer::Reader::operator>><float>(float&) /home/cdda/git/pioneer/src/scenegraph/Serializer.h:176
    #2 0x10d6257 in Serializer::Reader::readObject(vector3<float>&) /home/cdda/git/pioneer/src/scenegraph/Serializer.h:166
    #3 0x10d6257 in vector3<float> Serializer::Reader::obj<vector3<float> >() /home/cdda/git/pioneer/src/scenegraph/Serializer.h:115
    #4 0x10d6257 in Serializer::Reader::Vector3f() /home/cdda/git/pioneer/src/scenegraph/Serializer.h:206
    #5 0x10d6257 in SceneGraph::Thruster::Load(SceneGraph::NodeDatabase&) /home/cdda/git/pioneer/src/scenegraph/Thruster.cpp:133
    #6 0x21555d1 in std::function<SceneGraph::Node* (SceneGraph::NodeDatabase&)>::operator()(SceneGraph::NodeDatabase&) const /usr/include/c++/13/bits/std_function.h:591
    #7 0x21555d1 in SceneGraph::BinaryConverter::LoadNode(Serializer::Reader&) /home/cdda/git/pioneer/src/scenegraph/BinaryConverter.cpp:445
    #8 0x2155dec in SceneGraph::BinaryConverter::LoadNode(Serializer::Reader&) /home/cdda/git/pioneer/src/scenegraph/BinaryConverter.cpp:461
    #9 0x2155dec in SceneGraph::BinaryConverter::LoadNode(Serializer::Reader&) /home/cdda/git/pioneer/src/scenegraph/BinaryConverter.cpp:461
    #10 0x2155dec in SceneGraph::BinaryConverter::LoadNode(Serializer::Reader&) /home/cdda/git/pioneer/src/scenegraph/BinaryConverter.cpp:461
    #11 0x216046e in SceneGraph::BinaryConverter::CreateModel(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, Serializer::Reader&) /home/cdda/git/pioneer/src/scenegraph/BinaryConverter.cpp:244
    #12 0x216329a in SceneGraph::BinaryConverter::Load(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, RefCountedPtr<FileSystem::FileData>) /home/cdda/git/pioneer/src/scenegraph/BinaryConverter.cpp:165
    #13 0x2165304 in SceneGraph::BinaryConverter::Load(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) /home/cdda/git/pioneer/src/scenegraph/BinaryConverter.cpp:212
    #14 0x2166584 in SceneGraph::BinaryConverter::Load(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) /home/cdda/git/pioneer/src/scenegraph/BinaryConverter.cpp:151
    #15 0x1ceb013 in SceneGraph::Loader::LoadModel(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) /home/cdda/git/pioneer/src/scenegraph/Loader.cpp:166
    #16 0x1cee284 in SceneGraph::Loader::LoadModel(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) /home/cdda/git/pioneer/src/scenegraph/Loader.cpp:136
    #17 0x188cebe in ModelCache::FindModel(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) /home/cdda/git/pioneer/src/ModelCache.cpp:25
    #18 0x6d6879 in Pi::FindModel(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, bool) /home/cdda/git/pioneer/src/Pi.cpp:1174
    #19 0x1719e3f in Intro::Intro(Graphics::Renderer*, int, int) /home/cdda/git/pioneer/src/Intro.cpp:50
    #20 0x6cc315 in MainMenu::Start() /home/cdda/git/pioneer/src/Pi.cpp:662
    #21 0x4ddc99 in Application::StartLifecycle() /home/cdda/git/pioneer/src/core/Application.cpp:118
    #22 0x4e0d0b in Application::Run() /home/cdda/git/pioneer/src/core/Application.cpp:180
    #23 0x4947f6 in main /home/cdda/git/pioneer/src/main.cpp:180
    #24 0x7f76adf61149 in __libc_start_call_main (/lib64/libc.so.6+0x28149) (BuildId: 788cdd41a15985bf8e0a48d213a46e07d58822df)
    #25 0x7f76adf6120a in __libc_start_main_impl (/lib64/libc.so.6+0x2820a) (BuildId: 788cdd41a15985bf8e0a48d213a46e07d58822df)
    #26 0x4c0364 in _start (/home/cdda/git/pioneer/build/pioneer+0x4c0364) (BuildId: 0b596787b6ec3e0de0d5dbbe9321ec7a8c870f56)
```

### Expected behaviour

No misaligned reads

Note: the C++ standard allows compilers to assume misaligned reads (just like any other undefined behaviour) never happen. The compiler is than allowed to make an arbitrarily long and complex chain of logic deductions from that and use this information to mangle your code until it is completely unrecognisable. We should probably fix this.

### Steps to reproduce

1. Install libasan, libasan-static, libubsan, libubsan-static Note: I am not sure which one is required so I just installed all of them.
1. *Make sure the build/ directory does not exist.* This is needed because cmake does not update CXXFLAGS and LDFLAGS for existing build directories.
1. `CXXFLAGS="-fsanitize=address,pointer-compare,pointer-subtract,undefined" LDFLAGS="$CXXFLAGS" cmake -S . -B build/` Note: this command assumes you are in the git root dirrectory rather than in build/
2. `make -C build/`
3. `make -C build/ build-data`
4. `UBSAN_OPTIONS=print_stacktrace=1 ./pioneer`

__My complier:__ g++ (GCC) 13.2.1 20231205 (Red Hat 13.2.1-6)

__My pioneer version (and OS):__ 8b02b623281a9a0168a4bee38e05268b3ed0fe9d built from source (and Fedora release 39)

__My output.txt (required) and game save (optional, but recommended)__ [stdout&stderr.txt](https://github.com/pioneerspacesim/pioneer/files/13749882/output.txt) (note: there was no output.txt so I just captured stdout&stderr). No save necessary - the errors happen before the game shows the main menu.

### Observations

I have found two places where we forgot to insert padding in the SGM format, but it would surprise me if there are not many more

1. Thruster::Save & Thruster::Load - need 3 bytes of padding after `linear` because float wants to be 4-byte aligned. Plus: we are missing 4 bytes of padding at the end - just in case *something* later in the file contains a double or int64.
https://github.com/pioneerspacesim/pioneer/blob/8b02b623281a9a0168a4bee38e05268b3ed0fe9d/src/scenegraph/Thruster.cpp#L130-L137
3. Writer::Blob & Reader::Blob - need to pad to the 8 byte boundary because the next field might need 8 byte alignment and there is no convenient way for the caller to determine the necessary amount of padding
https://github.com/pioneerspacesim/pioneer/blob/8b02b623281a9a0168a4bee38e05268b3ed0fe9d/src/scenegraph/Serializer.h#L180-L190

### Possible fixes

1. [Use memcpy() instead of reinterpret_cast()](https://stackoverflow.com/a/29856789/14516046)

        #include <cstring>
        float unalignedload(char const *packed)
        {
          float buffer;
          std::memcpy(&buffer, packed, sizeof(float));
          return buffer;
        }

1. Make the public API of Serializer::Writer and Serializer::Reader *always* insert padding to the 8 byte boundary *after* writing/reading. This might be somewhat inefficient in terms of file size, but is relatively easy to implement.
1. Make the public API of Serializer::Writer and Serializer::Reader calculate the minimum necessary padding for the next field and insert the padding *before* writing/reading
1. Fix Thruster::Save&Thruster::Load, Writer::Blob & Reader::Blob and many other places to insert&skip the necessary padding. This is _fragile_ - eventually someone will make a similar mistake again.
1. Stop reinventing the wheel and replace Serializer with https://capnproto.org, https://protobuf.dev or https://flatbuffers.dev

Note: every option other than 1 will require bumping `SGM_VERSION` to a new version.

### PR DESCRIPTION
**Pull request by Web-eWorks**
Amend the Scenegraph serialization interface to more correctly handle the unaligned reads required by the SGM data structure layout. While the unaligned reads are in practice not an issue, this provides some future proofing against future compiler "improvements" (read: backwards compatibility breakages) and means the code is more portable to architectures like ARM64 which have a hardware requirement of aligned reads.

Closes #5687.

### CODE REVIEW

File: src/scenegraph/Serializer.h [hunk 1]
```diff
@@ -149,7 +149,7 @@ namespace Serializer {
 				throw std::out_of_range("Serializer::Reader encountered truncated stream.");
 #endif
 
-			out = *reinterpret_cast<const T *>(m_at);
```
Comment (hexagonrecursion) [inline src/scenegraph/Serializer.h:152]: Did you forget `#include <cstring>` ?

Comment (Web-eWorks) [reply src/scenegraph/Serializer.h:152]: It's pulled in by other headers but wouldn't hurt to explicitly have declared here as well.
