### PR TITLE
Move the System Map to PiGUI

### LINKED ISSUE #4801: src/pigui/Face.h & src/gameui/Face.h both "export" the same enum
### Observed behaviour
After rescan enums with **scripts/scan_enums.py**, the project does not build and shows an error:

`enum_table.cpp:286:44: error: redefinition of ‘const EnumItem ENUM_GameUIFaceFlags []’
 const struct EnumItem ENUM_GameUIFaceFlags[] = {`

Comparing these two files, you can see that they contain the same instructions for the script:
https://github.com/pioneerspacesim/pioneer/blob/f7f4abd5ab22296fb9bf00c6676efdfa65fac3af/src/pigui/Face.h#L22
https://github.com/pioneerspacesim/pioneer/blob/f7f4abd5ab22296fb9bf00c6676efdfa65fac3af/src/gameui/Face.h#L25

The question is can we just rename **GameUI** to **PIGUI** in src/pigui/Face.h ?

### Expected behaviour
Successful recompilation after rescan.

### Steps to reproduce
1. run `./scripts/scan_enums.py --pattern="*.h" -r -o ./src/enum_table.cpp ./src`
2. run build

__My pioneer version (and OS):__
current master f7f4abd5ab22296fb9bf00c6676efdfa65fac3af

### PR DESCRIPTION
**Pull request by Gliese852**
The main idea of the interaction of lua side and C++ side is the same as in the worldview - the C++ View Class builds three-dimensional objects, some projected points are passed to the lua script, the lua script only works with screen coordinates.

The difference between the system view and the world view is that not all objects can have a physical body. If we examine a non-current star system, we see only system bodies that do not have physical bodies. Therefore, if for a world view you can simply create an array of physical bodies, this will not work in a system view.

To solve this problem, struct "Projectable" was created, into which you can write any point object, system body, ship, Lagrange point, apocenter, pericenter, etc. Now all these objects can be processed in a single array.

The names of the types of these objects are recorded in an enum, which is exported to a enum_table.cpp and read by the script as integers at the start. I thought it was better to avoid passing strings in such a hot place in the code. (runs for every object in every frame) Therefore,
type names are written and transmitted as integers.

All colors are now imported from lua: color index names are listed in the enum, which is exported to the enum_table.cpp. At event "onGameStart" the lua script reads these names and sends color values to the class. Now you can change colors at runtime. 

### Improvements/fixes:

- Fix zooming speeds.
- Fix ship's orbits in nonroot frame.
- Remove unused old gui objects.
- Landed ship are now spinning with the planet when rewinding time in a planner.
- Now you can center the view on any object, including the player’s ship.
- Add right-click context menu to center or set object as target. Therefore, to rotate the view, set the middle button.
- Add indicators for navigation target and combat target.

### Extra improvements/fixes (second commit):

- Now only those orbits whose radius is less than 1% of the screen width are not shown.
- Add smooth transition when click object.
- Improve system bodies orbits. 
- Fix that ..apsis and lagrange points were displayed in the wrong place.
- After rescanning enums, an error was found in the pigui/Face.h, fixed. fixes #4801 
- Some indentations to pass clang
- Add static_cast to Space.cpp, because it caused a warning at compilation.

### Changes in the files explained:

    SystemView.cpp, SystemView.h, system-view-ui.lua, lang/core/en.json

The whole thing, lots of changes. Now the system view draws only the orbits and the grid. In those places where the icons were drawn, instead of drawing, they are stored in an array, which is then requested from the lua.

    LuaEngine.cpp

Add a general function that returns the value of an any enum by name from an enum_table.cpp (for calling from a lua)

    Space.cpp

Add a notification for the systemview when the ship is removed from space, because it can be centered at this time, and an segmentation fault will occur.

    LuaSystemBody.cpp

Add attributes to determine the shape of the icon and set the navigation target.

    enum_table.cpp, enum_table.h

Rescanned enums to pass color settings and object types between Lua and C++.

    LuaGame.cpp

The float does not have enough accuracy to display time up to seconds, change to double.

    icons.svg, themes/default.lua

Add rotate view icon

### CODE REVIEW

File: data/pigui/modules/system-view-ui.lua [hunk 1]
```diff
@@ -0,0 +1,523 @@
...
+local Format = require 'Format'
+
+local Vector2 = _G.Vector2
+local lc = Lang.GetResource("core")
+
+local player = nil
+local colors = ui.theme.colors
+local icons = ui.theme.icons
+
+local mainButtonSize = Vector2(32,32)  * (ui.screenHeight / 1200)
```
Comment (Web-eWorks) [inline data/pigui/modules/system-view-ui.lua]: Please prefer the use of `ui.rescaleUI` over manually scaling by `ui.screenheight`. Among other reasons, it's easier to grep for the single `ui.rescaleUI` function when we eventually implement resizable windows.

File: data/pigui/modules/system-view-ui.lua [hunk 2]
```diff
@@ -0,0 +1,523 @@
...
+	+ itemSpacing.x * 2
+end
+
+local orbitPlannerWindowPos = Vector2(ui.screenWidth - calcWindowWidth(7), ui.screenHeight - calcWindowHeight(7, 3, 2))
+
+local function showOrbitPlannerWindow()
+	ui.setNextWindowPos(orbitPlannerWindowPos, "Always")
+	ui.withStyleColors({["WindowBg"] = svColor.WINDOW_BACK}, function()
+			ui.window("OrbitPlannerWindow", {"NoTitleBar", "NoResize", "NoFocusOnAppearing", "NoBringToFrontOnFocus", "NoSavedSettings", "AlwaysAutoResize"},
+								function()
```
Comment (Web-eWorks) [inline data/pigui/modules/system-view-ui.lua]: Looks like there's some indentation weirdness going on here. We use a single level of tabbed (not spaced!) indentation in our lua scripts for each scope change; right here, you have what looks like two tabs of indentation on the previous line followed by an extra three tabs on this line.

I'd appreciate it if you could normalize your indentation. :smile:

File: data/pigui/themes/default.lua [hunk 3]
```diff
@@ -191,10 +192,10 @@ theme.icons = {
    display_navtarget = 121,
    alert1 = 122,
    alert2 = 123,
-	 ecm_advanced = 124,
-	 systems_management = 125,
-	 distance = 126,
-	 filter = 127,
+   ecm_advanced = 124,
```
Comment (Web-eWorks) [inline data/pigui/themes/default.lua]: Same thing here, this file should all be one tab of indentation. If you could update that in a separate commit, I'd really appreciate it.

File: src/lua/LuaEngine.cpp [hunk 4]
```diff
@@ -1082,6 +1092,329 @@ static int l_engine_get_sector_map_factions(lua_State *l)
 	return 1;
 }
 
+static int l_engine_system_map_set_color(lua_State *l)
+{
+	SystemView *sv = Pi::game->GetSystemView();
```
Comment (Web-eWorks) [inline src/lua/LuaEngine.cpp]: Please prefer making `SystemMapSetColor` and its ilk member functions on a new `LuaObject<SystemView>` class instead, and add the accessor for the instance of the SystemView to the `LuaGame` interface. I'd much prefer that we don't start C-style namespacing functions and putting them in `LuaEngine` when they don't actually need to be there.

Yes, I know that's how the SectorMap does it right now, but it really shouldn't be done that way.

File: data/pigui/modules/system-view-ui.lua (hunk 1 above)
Comment (Gliese852) [reply data/pigui/modules/system-view-ui.lua]: I think i fixed it. 704ec4a66cb4f3467d3897b703a73a8687356223

File: data/pigui/modules/system-view-ui.lua (hunk 2 above)
Comment (Gliese852) [reply data/pigui/modules/system-view-ui.lua]: Sorry, I forgot to indent the code. Fixed 704ec4a66cb4f3467d3897b703a73a8687356223

File: data/pigui/themes/default.lua (hunk 3 above)
Comment (Gliese852) [reply data/pigui/themes/default.lua]: Most likely this file, together with icons.svg, will go to another PR.

Comment (Gliese852) [reply data/pigui/themes/default.lua]: These files are no longer here.

File: src/lua/LuaEngine.cpp (hunk 4 above)
Comment (Gliese852) [reply src/lua/LuaEngine.cpp]: Made in 7dfc75ba29538d8d142bc7b88e500906ff2ad93c

**Comment by impaktor** [comment]
@Gliese852 you need to give a shout when you feel this PR is ready for re-review

**Comment by Gliese852** [comment]
@impaktor I fixed all the errors, tell me please how to inform about it.

**Comment by impaktor** [comment]
> Add right-click context menu to center or set object as target. Therefore, to rotate the view, set the middle button.

I think this should be discussed, as it feels very strange (to me), to not have rotation on right mouse button, like it is in WorldView and SectorView. I thought it was a bug, and didn't realize there was a middle mouse button.

Could one have rotation on RMB, and move functinality on middle mouse button to someplace else? What does the rest of you think? There is logic in middle mouse button, since it's already used for zoom in/out, but having them different on different views is strange. And many people don't have middle mouse button, I suspect, if on a laptop, like me.

I haven't looked at the code (yet?), but seems to be a lot of improvements_

**Comment by Gliese852** [comment]
@impaktor In the worldview, the camera rotates with the middle button, and the ship rotates with the right button.  In fact, I play a lot with a view from the outside, so it’s just convenient for me to rotate the camera in a worldview and in a systemview using a wheel.

In fact, I do not have a firm position, as it should be, this is a question of one line of code.

On the other hand, to play without a mouse, can it be better to make on-screen buttons to rotate the view?  And maybe assign physical keys.

**Comment by nozmajner** [comment]
@Gliese852 I think it should be consistent with the other views. 
Middle mouse sounds reasonablew for rotation to me, and having physical keys for it would be nice as well. 
Rigth mouse then could be free for future right-click menu functionality similar to worldview.
I think on-screen buttons would be an overkill, and would only add clutter. But maybe in a simplified way: one button for rotation, it rotates the view when you clicked on it until you release the mouse button?

**Comment by impaktor** [comment]
> But maybe in a simplified way: one button for rotation, it rotates the view when you clicked on it until you release the mouse button?

Sounds like a good idea. @nozmajner maybe there should be an icon for such a button?

Either way, I think this PR probably needs to touch sectorview as well, to make rotation consistent. Sorry to expand the scope of this.

**Comment by Gliese852** [comment]
@impaktor @nozmajner Maybe then do this: make one on-screen button for zoom, one on-screen button for rotation, and assign numpad keys. And do the same in the sectorview?

File: src/lua/LuaSystemView.cpp [hunk 5]
```diff
@@ -0,0 +1,359 @@
...
+	return std::abs(a.x - b.x) < gain.x && std::abs(a.y - b.y) < gain.y
+		// we don’t want to group objects that simply overlap and are located at different distances
+		// therefore, depth is also taken into account, we have z_NDC (normalized device coordinates)
+		// in order to make a strict translation of delta z_NDC into delta "pixels", one also needs to know
+		// the z coordinates in the camera space. I plan to implement this later
+		// at the moment I just picked up a number that works well (6.0)
+		&& std::abs(a.z - b.z) * Graphics::GetScreenWidth() * 6.0 < gain.x;
+};
+
+static int l_systemview_get_projected_grouped(lua_State *l)
```
[the remark this answers is not in the document]
Comment (Gliese852) [reply src/lua/LuaSystemView.cpp]: Done!

File: src/lua/LuaSystemView.cpp [hunk 6]
```diff
@@ -0,0 +1,359 @@
...
+	double t = sv->GetOrbitPlannerTime();
+	LuaPush<double>(l, t);
+	return 1;
+}
+
+static int l_systemview_accelerate_time(lua_State *l)
+{
+	SystemView *sv = LuaObject<SystemView>::CheckFromLua(1);
+	if (lua_isnil(l, 2))
+		sv->OnClickRealt();
```
[the remark this answers is not in the document]
Comment (Gliese852) [reply src/lua/LuaSystemView.cpp]: Done!

**Comment by Gliese852** [comment]
@impaktor @nozmajner I implemented on-screen buttons for zooming and rotating in the system Map in the last commit.

**Comment by impaktor** [comment]
Doesn't build on my system:
```
/usr/bin/ld: src/lua/libpioneer-lua.a(Lua.cpp.o): in function `Lua::InitModules()':
/home/me/usr/src/pioneer/src/lua/Lua.cpp:75: undefined reference to `LuaObject<SystemView>::RegisterClass()'
/usr/bin/ld: src/lua/libpioneer-lua.a(LuaGame.cpp.o): in function `LuaObjectBase::LuaObjectBase(char const*)':
/home/me/usr/src/pioneer/src/lua/LuaObject.h:119: undefined reference to `LuaObject<SystemView>::s_type'
```

**Comment by nozmajner** [comment]
```1>------ Build started: Project: scenegraph, Configuration: Release x64 ------
1>cl : command line warning D9035: option 'Gm' has been deprecated and will be removed in a future release
1>ModelSkin.cpp
1>C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\ucrt\corecrt_math_defines.h(22,1): warning C4005: 'M_PI': macro redefinition
1>D:\pioneer\build\pioneer-thirdparty\win32\include\SDL_stdinc.h(499): message : see previous definition of 'M_PI'
1>D:\pioneer\build\pioneer-ecraven-systemview-squashed\src\scenegraph\Serializer.h(48,1): warning C4267: 'argument': conversion from 'size_t' to 'const T', possible loss of data
1>        with
1>        [
1>            T=Uint32
1>        ]
1>D:\pioneer\build\pioneer-ecraven-systemview-squashed\src\scenegraph\Serializer.h(59,1): warning C4267: 'initializing': conversion from 'size_t' to 'Uint32', possible loss of data
1>D:\pioneer\build\pioneer-ecraven-systemview-squashed\src\scenegraph\Serializer.h(83,1): warning C4267: 'argument': conversion from 'size_t' to 'Uint32', possible loss of data
1>D:\pioneer\build\pioneer-ecraven-systemview-squashed\src\scenegraph\ModelSkin.cpp(114,37): error C2593: 'operator =' is ambiguous
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.25.28610\include\xstring(2591,19): message : could be 'std::basic_string<char,std::char_traits<char>,std::allocator<char>> &std::basic_string<char,std::char_traits<char>,std::allocator<char>>::operator =(std::initializer_list<_Elem>)'
1>        with
1>        [
1>            _Elem=char
1>        ]
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.25.28610\include\xstring(2492,19): message : or       'std::basic_string<char,std::char_traits<char>,std::allocator<char>> &std::basic_string<char,std::char_traits<char>,std::allocator<char>>::operator =(std::basic_string<char,std::char_traits<char>,std::allocator<char>> &&) noexcept'
1>D:\pioneer\build\pioneer-ecraven-systemview-squashed\src\scenegraph\ModelSkin.cpp(114,37): message : while trying to match the argument list '(std::string, nlohmann::basic_json<std::map,std::vector,std::string,bool,int64_t,uint64_t,double,std::allocator,nlohmann::adl_serializer>)'
1>D:\pioneer\build\pioneer-ecraven-systemview-squashed\src\scenegraph\ModelSkin.cpp(117,35): error C2593: 'operator =' is ambiguous
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.25.28610\include\xstring(2591,19): message : could be 'std::basic_string<char,std::char_traits<char>,std::allocator<char>> &std::basic_string<char,std::char_traits<char>,std::allocator<char>>::operator =(std::initializer_list<_Elem>)'
1>        with
1>        [
1>            _Elem=char
1>        ]
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.25.28610\include\xstring(2492,19): message : or       'std::basic_string<char,std::char_traits<char>,std::allocator<char>> &std::basic_string<char,std::char_traits<char>,std::allocator<char>>::operator =(std::basic_string<char,std::char_traits<char>,std::allocator<char>> &&) noexcept'
1>D:\pioneer\build\pioneer-ecraven-systemview-squashed\src\scenegraph\ModelSkin.cpp(117,35): message : while trying to match the argument list '(std::string, nlohmann::basic_json<std::map,std::vector,std::string,bool,int64_t,uint64_t,double,std::allocator,nlohmann::adl_serializer>)'
1>Done building project "newmodel.vcxproj" -- FAILED.
2>------ Build started: Project: pioneer, Configuration: Release x64 ------
2>cl : command line warning D9025: overriding '/sdl-' with '/GS-'
2>cl : command line warning D9025: overriding '/sdl-' with '/GS-'
2>cl : command line warning D9025: overriding '/sdl-' with '/GS-'
2>Body.cpp
2>Frame.cpp
2>cl : command line warning D9025: overriding '/sdl-' with '/GS-'
2>Ship.cpp
2>D:\pioneer\build\pioneer-ecraven-systemview-squashed\src\Frame.cpp(31,28): warning C4267: 'argument': conversion from 'size_t' to 'int', possible loss of data
2>D:\pioneer\build\pioneer-ecraven-systemview-squashed\src\Frame.cpp(36,49): warning C4267: '=': conversion from 'size_t' to 'int', possible loss of data
2>D:\pioneer\build\pioneer-ecraven-systemview-squashed\src\Frame.cpp(61,28): warning C4267: 'argument': conversion from 'size_t' to 'int', possible loss of data
2>D:\pioneer\build\pioneer-ecraven-systemview-squashed\src\Frame.cpp(170,30): warning C4267: 'argument': conversion from 'size_t' to 'int', possible loss of data
2>D:\pioneer\build\pioneer-ecraven-systemview-squashed\src\Frame.cpp(195,33): error C2593: 'operator =' is ambiguous
2>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.25.28610\include\xstring(2591,19): message : could be 'std::basic_string<char,std::char_traits<char>,std::allocator<char>> &std::basic_string<char,std::char_traits<char>,std::allocator<char>>::operator =(std::initializer_list<_Elem>)'
2>        with
2>        [
2>            _Elem=char
2>        ] (compiling source file ..\..\src\Frame.cpp)
2>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.25.28610\include\xstring(2492,19): message : or       'std::basic_string<char,std::char_traits<char>,std::allocator<char>> &std::basic_string<char,std::char_traits<char>,std::allocator<char>>::operator =(std::basic_string<char,std::char_traits<char>,std::allocator<char>> &&) noexcept' (compiling source file ..\..\src\Frame.cpp)
2>D:\pioneer\build\pioneer-ecraven-systemview-squashed\src\Frame.cpp(195,33): message : while trying to match the argument list '(std::string, const nlohmann::basic_json<std::map,std::vector,std::string,bool,int64_t,uint64_t,double,std::allocator,nlohmann::adl_serializer>)'
2>D:\pioneer\build\pioneer-ecraven-systemview-squashed\src\Frame.cpp(261,30): warning C4267: 'argument': conversion from 'size_t' to 'int', possible loss of data
2>D:\pioneer\build\pioneer-ecraven-systemview-squashed\src\Body.cpp(47,29): error C2593: 'operator =' is ambiguous
2>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.25.28610\include\xstring(2591,19): message : could be 'std::basic_string<char,std::char_traits<char>,std::allocator<char>> &std::basic_string<char,std::char_traits<char>,std::allocator<char>>::operator =(std::initializer_list<_Elem>)'
2>        with
2>        [
2>            _Elem=char
2>        ] (compiling source file ..\..\src\Body.cpp)
2>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.25.28610\include\xstring(2492,19): message : or       'std::basic_string<char,std::char_traits<char>,std::allocator<char>> &std::basic_string<char,std::char_traits<char>,std::allocator<char>>::operator =(std::basic_string<char,std::char_traits<char>,std::allocator<char>> &&) noexcept(<expr>)' (compiling source file ..\..\src\Body.cpp)
2>D:\pioneer\build\pioneer-ecraven-systemview-squashed\src\Body.cpp(47,29): message : while trying to match the argument list '(std::string, nlohmann::basic_json<std::map,std::vector,std::string,bool,int64_t,uint64_t,double,std::allocator,nlohmann::adl_serializer>)'
2>D:\pioneer\build\pioneer-ecraven-systemview-squashed\src\Ship.cpp(191,31): error C2593: 'operator =' is ambiguous
2>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.25.28610\include\xstring(2591,19): message : could be 'std::basic_string<char,std::char_traits<char>,std::allocator<char>> &std::basic_string<char,std::char_traits<char>,std::allocator<char>>::operator =(std::initializer_list<_Elem>)'
2>        with
2>        [
2>            _Elem=char
2>        ] (compiling source file ..\..\src\Ship.cpp)
2>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.25.28610\include\xstring(2492,19): message : or       'std::basic_string<char,std::char_traits<char>,std::allocator<char>> &std::basic_string<char,std::char_traits<char>,std::allocator<char>>::operator =(std::basic_string<char,std::char_traits<char>,std::allocator<char>> &&) noexcept' (compiling source file ..\..\src\Ship.cpp)
2>D:\pioneer\build\pioneer-ecraven-systemview-squashed\src\Ship.cpp(191,31): message : while trying to match the argument list '(std::string, nlohmann::basic_json<std::map,std::vector,std::string,bool,int64_t,uint64_t,double,std::allocator,nlohmann::adl_serializer>)'
2>Done building project "pioneer.vcxproj" -- FAILED.
========== Build: 0 succeeded, 2 failed, 13 up-to-date, 0 skipped ==========
```

File: src/Pi.h [hunk 7]
```diff
@@ -92,6 +92,9 @@ class Pi {
 	static void SetMouseGrab(bool on);
 	static bool DoingMouseGrab() { return doingMouseGrab; }
 
+	static void EnableViewTransformationMode() { doingViewTransformation = true; }
+	static void DisableViewTransformationMode() { doingViewTransformation = false; }
+
```
Comment (Web-eWorks) [inline src/Pi.h]: Please don't do this. We don't want to introduce any more functionality into `Pi.cpp` that isn't absolutely required, as it's already extremely painful to maintain this giant lump of singleton code.

In this case, please prefer using `ImGui::IsMouseDragging` and `ImGui::GetMouseDragDelta` (which aren't currently exposed to pigui) and pass the input into the systemview yourself. Among other reasons, this will reduce code duplication once mouse events become a first-class part of the input system, and it also doesn't add yet another global function to `Pi.cpp` that's only used for *one thing*.

Alternatively, you can expose `ImGui::CaptureMouseFromApp` (possibly with a different name and/or binding point), and use that functionality to keep from consuming mouse events while the user is rotating, though *stopping* rotating might be difficult.

**Comment by Web-eWorks** [comment]
Regarding the handling of rotation/zoom mode, here are some words transcribed from IRC:
```
sturnclaw   Gliese852: apologies if my comment comes across a little harsh
sturnclaw   I haven't gotten time to review the lua code yet, but
            doingViewTransformation stuck out to me; please definitely don't
            touch Pi.cpp unless completely necessary
sturnclaw   The current way of manually checking SDL_MOUSE_BUTTON_LEFT to
            determine if we need to rotate a view should be considered
            deprecated, I just haven't had time to build the replacement system
sturnclaw   For now, I'd recommend you pass the mouse movement from imgui
            itself; there's a hysteresis value for tiny drags to avoid
            micromovements (e.g. single clicks addding a tiny offset)
sturnclaw   In the future, you're going to need to consume input from more than
            just the mouse movement; we'd like to be able to bind joystick axes
            and gamepad sticks and buttons etc. to rotate the view
sturnclaw   I'm definitely going to implement a "capture mode" that lets the
            input system take priority over imgui for mouse motion
sturnclaw   Actually, I'll try to hammer that out tomorrow so you can rework
            your PR to use it
sturnclaw   So the code flow would become if ui.IsItemClicked() then
            systemView:RotationMode(true) end
sturnclaw   and SystemView::RotationMode(bool enabled) would call
            Input::SetCaptureMouse(enabled), set m_rotateMode = enabled, and
            then the normal control handling would happen
sturnclaw   I'd caution you against using string comparisons with e.g.
            SetVisibility by the way; especially for the Rotate and Zoom modes
            you really should be using a dedicated function call rather than
            overloading a visibility mode
```

I've settled on implementing a "Capture Mouse" setting to the input system to unify the various methods of handling exclusive mouse input and pre-empting ImGui's mouse handling; I'll get that coded up tomorrow as I don't expect many issues with implementing it. I'd recommend you rebase your PR to remove the changes to Pi.h/Pi.cpp once that's merged (which will be very soon after I get it working).

File: src/lua/LuaSystemView.cpp [hunk 8]
```diff
@@ -0,0 +1,417 @@
...
+		{ "GetOrbitPlannerStartTime", l_systemview_get_orbit_planner_start_time },
+		{ "GetOrbitPlannerTime", l_systemview_get_orbit_planner_time },
+		{ "AccelerateTime", l_systemview_accelerate_time },
+		{ "SetSelectedObject", l_systemview_set_selected_object },
+		{ "SetVisibility", l_systemview_set_visibility },
+		{ "SetColor", l_systemview_set_color },
+
+		{ "TransferPlannerAdd", l_systemview_transfer_planner_add },
+		{ "TransferPlannerGet", l_systemview_transfer_planner_get },
+		{ "TransferPlannerReset", l_systemview_transfer_planner_reset }
```
Comment (Web-eWorks) [inline src/lua/LuaSystemView.cpp]: You're missing a `{ NULL, NULL }` terminator at the end of this list. On my system (using AVX2-accelerated strlen()), this code crashes the entire application when the terminator is not present.

File: src/lua/LuaInput.cpp [hunk 9]
```diff
@@ -268,6 +280,8 @@ void LuaInput::Register()
 		{ "SetMouseYInverted", l_input_set_mouse_y_inverted },
 		{ "GetJoystickEnabled", l_input_get_joystick_enabled },
 		{ "SetJoystickEnabled", l_input_set_joystick_enabled },
+		{ "EnableViewTransformationMode", l_input_enable_view_transformation_mode },
```
Comment (Web-eWorks) [inline src/lua/LuaInput.cpp]: Once #4842 is merged, I'd recommend coalescing these to `SetCapturingInput(bool)`, internally calling `Pi::input.SetCapturingInput()`.

File: src/SystemView.h [hunk 10]
```diff
@@ -9,12 +9,17 @@
 #include "graphics/Drawables.h"
 #include "matrix4x4.h"
 #include "vector3.h"
+#include "lua/LuaTable.h"
+#include "lua/LuaPiGui.h"
```
Comment (Web-eWorks) [inline src/SystemView.h]: If this include isn't required to be in the header file because a class member is using it, please move it to the cpp source file. This helps keep the build (and incremental recompile) time lower!

File: src/SystemView.cpp [hunk 11]
```diff
@@ -1069,28 +661,128 @@ void SystemView::DrawGrid()
...
+		m_shipDrawing = ORBITS;
+	else if (param == "ZOOM_ON")
+		m_zoomView = true;
+	else if (param == "ROTATE_ON")
+		m_rotateView = true;
+	else if (param == "MOUSE_UP")
+	{
+		m_rotateView = false;
+		m_zoomView = false;
+	}
```
Comment (Web-eWorks) [inline src/SystemView.cpp]: Please definitely separate these into their own functions taking boolean arguments. We definitely don't want to be comparing strings if all we're doing is toggling booleans, especially with any regularity!

File: data/pigui/modules/system-view-ui.lua [hunk 12]
```diff
@@ -0,0 +1,524 @@
...
+					if navTarget == mainObject.ref then player:SetNavTarget(nil) end
+					player:SetCombatTarget(mainObject.ref)
+				end
+			end)
+		end
+		-- mouse release handler
+		if ui.isMouseReleased(0) then
+			systemView:SetVisibility("MOUSE_UP")
+			Input:DisableViewTransformationMode()
+		end
```
Comment (Web-eWorks) [inline data/pigui/modules/system-view-ui.lua]: I'd *strongly* recommend you move this functionality to SystemView.cpp instead; see PlayerShipController.cpp in #4842 for an example implementation.

File: data/pigui/modules/system-view-ui.lua [hunk 13]
```diff
@@ -0,0 +1,524 @@
...
+			if ui.coloredSelectedIconButton(icons.toggle_lagrange, mainButtonSize, showLagrangePoints, mainButtonFramePadding, svColor.BUTTON_BACK, svColor.BUTTON_INK, "Show Lagrange points") then
+				show_lagrange = nextShowLagrange[show_lagrange]
+				systemView:SetVisibility(show_lagrange);
+			end
+			ui.sameLine()
+			ui.coloredSelectedIconButton(icons.search_lens,mainButtonSize, false, mainButtonFramePadding, svColor.BUTTON_BACK, svColor.BUTTON_INK, "Zoom")
+			if ui.isItemActive() then
+				Input:EnableViewTransformationMode()
+				systemView:SetVisibility("ZOOM_ON")
+			end
```
Comment (Web-eWorks) [inline data/pigui/modules/system-view-ui.lua]:
```suggestion
			systemView:SetZoomMode(ui.isItemActive())
```

File: data/pigui/modules/system-view-ui.lua [hunk 14]
```diff
@@ -0,0 +1,524 @@
...
+			ui.sameLine()
+			ui.coloredSelectedIconButton(icons.rotate_view, mainButtonSize, false, mainButtonFramePadding, svColor.BUTTON_BACK, svColor.BUTTON_INK, "Rotate")
+			if ui.isItemActive() then
+				Input:EnableViewTransformationMode()
+				systemView:SetVisibility("ROTATE_ON")
+			end
```
Comment (Web-eWorks) [inline data/pigui/modules/system-view-ui.lua]:
```suggestion
			systemView:SetRotateMode(ui.isItemActive())
```

**Comment by impaktor** [comment]
Nice. I wonder if the magnify and rotate buttons could be placed somewhere else? E.g. top right corner? @nozmajner thoughts? (see screenshot below)

It's still pretty strange to use different buttons for rotation in sector view vs. system view. I'd suggest making sector view work the same way as system view, and also add magnifying glass and rotate button to top right corner.

Other than that, good work!

2020-03-24-194415_1600x900_scrot

**Comment by Gliese852** [comment]
@impaktor Yes, I plan to add control from the numeric keypad (as in the worldview), and then, when it works well in the systemview, do the same in the sectorview.

The location of the buttons is definitely not final, it's just the way @ecraven had it in the original PR.

**Comment by impaktor** [comment]
> I plan to add control from the numeric keypad

I was more thinking about the RMB / MMB behaving differently / opposite in system view vs. sector view.

**Comment by Gliese852** [comment]
@impaktor Oh, yes, I just didn’t put it that way, I had in mind all the controls including the keyboard, mouse and on-screen buttons will be copied from systemview to sectorview.

**Comment by impaktor** [comment]
OK. Sounds good. (right click menu for sectore view would be nice as well, but could be outside the scope of this PR, as long as RMB/MMB inconcistency is sorted out in this PR).

I played a bit more with this branch, and updated the screenshot in my previous post to show more features. Very nice.

File: src/lua/LuaSystemView.cpp (hunk 8 above)
Comment (Gliese852) [reply src/lua/LuaSystemView.cpp]: Done in e32068af86141c1035fea259612b3dec5fed1959!

File: src/Pi.h (hunk 7 above)
Comment (Gliese852) [reply src/Pi.h]: Done in d9ac37975b2f4161bc1350600ca22d3fe5cedf98!

File: src/lua/LuaInput.cpp (hunk 9 above)
Comment (Gliese852) [reply src/lua/LuaInput.cpp]: I generally deleted these functions from the LuaInput.cpp, because now it works through the SystemView.cpp. See d9ac37975b2f4161bc1350600ca22d3fe5cedf98

File: src/SystemView.h (hunk 10 above)
Comment (Gliese852) [reply src/SystemView.h]: Done! See d9ac37975b2f4161bc1350600ca22d3fe5cedf98

File: src/SystemView.cpp (hunk 11 above)
Comment (Gliese852) [reply src/SystemView.cpp]: Done! See d9ac37975b2f4161bc1350600ca22d3fe5cedf98

File: data/pigui/modules/system-view-ui.lua (hunk 12 above)
Comment (Gliese852) [reply data/pigui/modules/system-view-ui.lua]: Done! See d9ac37975b2f4161bc1350600ca22d3fe5cedf98

File: data/pigui/modules/system-view-ui.lua (hunk 13 above)
Comment (Gliese852) [reply data/pigui/modules/system-view-ui.lua]: Done! See d9ac37975b2f4161bc1350600ca22d3fe5cedf98

File: data/pigui/modules/system-view-ui.lua (hunk 14 above)
Comment (Gliese852) [reply data/pigui/modules/system-view-ui.lua]: Done! See d9ac37975b2f4161bc1350600ca22d3fe5cedf98

**Comment by Web-eWorks** [comment]
...Those comments were supposed to be part of a review, but apparently Github doesn't do reviews unless you're viewing the whole PR's history and not just a single commit.

Looking good so far, just some minor changes and I'll try to get this merged in ASAP!

**Comment by Gliese852** [comment]
@Web-eWorks I implemented the latest recommendations in the commit ba3bbe8372116c3704719284b05470634e2731dc

**Comment by impaktor** [comment]
Looks like commit history could need some squashing, ideally

**Comment by Gliese852** [comment]
@impaktor Can squash-merge solve this problem? or it should be squashed in advance for some reason?

**Comment by impaktor** [comment]
Well, squash-merge makes the whole thing into a single commit, which is a but brutal on the other end, as I assume you've had to implement various titbits to make this whole PR come together, so ideally they shuld be kept as separate commits, but the small fixes you've done in the review process should be squashed into where the code they fixed was introduced.

...If we are to appeal to our perfectionsit side.

**Comment by impaktor** [comment]
Hmm, this PR is showing the Travis build, so only new PRs lack it? (general statement)

**Comment by impaktor** [comment]
Just to repeat what I wrote in IRC, tested it, very nice, but I'd:
- Grid is a bit (or a lot) too dark, maybe use same colors as in sector view?
- Would it be possible to (as separate commit) make middle mouse in sector view behave the same as in this new system view, for consistency?
- Maybe here, or in another PR, add the rotation icon/function to sector view?

**Comment by Gliese852** [comment]
@impaktor I planned to do a sector view in another PR (next)
