### PR TITLE
ModalWindow class that allows nesting

### LINKED ISSUE #4755: Save game dialog does not appear
### Observed behaviour

The save game dialog does not open when pressing the save button, i.e. flight UI -> Esc -> "Save" button.
After pressing the save button once, also Load Game from the main menu stops working.
quicksave via Ctrl-F9 works fine.

__My pioneer version (and OS):__
d0f26555 (current master)

last bug free:
d016f7a5 (Nov 16 2019)

### PR DESCRIPTION
**Pull request by vakhoir**
Fixes #4755 closes #4765 

I created a class that keeps track of and draws modal windows, so each window can be open from any script without having to worry about what was opened before. It should make writing modals a bit more intuitive.

### CODE REVIEW

**Comment by vakhoir** [comment]
In testing the ShipMarket view I noticed the Market widget I wrote wasn't blocked by modal popups, this is now fixed. Also added a check for not double-opening popups, which screws up to popup stack on the c++ side, and leads to all sorts of issues.

File: data/pigui/libs/modal-win.lua [hunk 1]
```diff
@@ -0,0 +1,81 @@
...
+	for i=#modalStack, self.stackIdx, -1 do
+		modalStack[i].stackIdx = -1
+		modalStack[i].isOpen = false
+		ui.closeCurrentPopup()
+		table.remove(modalStack, i)
+	end
+end
+
+local drawModals
+drawModals = function(idx)
```
Comment (Web-eWorks) [inline data/pigui/libs/modal-win.lua]: @vakhoir per the lua reference manual, `local function drawModals(idx)` is syntactic sugar for `local drawModals; drawModals = function(idx)`, so this construct is redundant.
Just FYI!

File: data/pigui/libs/modal-win.lua [hunk 2]
```diff
@@ -0,0 +1,81 @@
...
+
+local modals = {}
+local modalStack = {}
+
+local ModalWindow = {}
+
+function ModalWindow.New(name, innerHandler, outerHandler, flags)
+	local self = {
+		name = name,
+		flags = flags or {"NoTitleBar", "NoResize", "AlwaysAutoResize", "NoMove"},
```
Comment (Web-eWorks) [inline data/pigui/libs/modal-win.lua]: I'd recommend you use the new WindowFlags helper class to create this set of flags once at file scope and simply set `flags = flags or defaultFlags`. This avoids the extra memory cost of the flags table, and prevents the table from having to be parsed once a frame!

File: data/pigui/libs/modal-win.lua [hunk 3]
```diff
@@ -0,0 +1,81 @@
...
+		stackIdx = -1,
+		isOpen = false,
+		innerHandler = innerHandler,
+		outerHandler = outerHandler,
```
Comment (Web-eWorks) [inline data/pigui/libs/modal-win.lua]: I'd also recommend that you set `outerHandler = outerHandler or function(drawFn) drawFn() end` instead of deferring the check until the end of the table creation. You save about five lines that way :D

File: data/pigui/modules/saveloadgame.lua [hunk 4]
```diff
@@ -98,50 +99,40 @@ local function showSaveFiles()
...
 
-local function savedGameWindow()
-	if ui.showSavedGameWindow then
-		if not popupOpened then
-			popupOpened = true
-			ui.openPopup("LoadGame")
-		end
+ui.saveLoadWindow = ModalWindow.New("LoadGame", function()
+	local mode
+	mode = ui.saveLoadWindow.mode == 'SAVE' and lui.SAVE or lui.LOAD
```
Comment (Web-eWorks) [inline data/pigui/modules/saveloadgame.lua]: Is there a reason why you're declaring `mode` and then assigning a line later? This should be all one line.

File: data/pigui/modules/saveloadgame.lua [hunk 5]
```diff
@@ -98,50 +99,40 @@ local function showSaveFiles()
...
+	optionTextButton(mode, nil, selectedSave~=nil, closeAndLoadOrSave)
```
Comment (Web-eWorks) [inline data/pigui/modules/saveloadgame.lua]: Minor nitpick, but please space around your operators like this. Also if selectedSave is guaranteed to be a "truthy" value when present, use `not selectedSave` instead; it's a little shorter and much easier for the reader to parse.
```suggestion
	optionTextButton(mode, nil, selectedSave ~= nil, closeAndLoadOrSave)
```

File: data/pigui/modules/settings-window.lua [hunk 6]
```diff
@@ -509,76 +507,62 @@ local optionsTabs = {
 	["controls"]=showControlsOptions
 }
 
-local optionModalOpen = false
-
-local function optionsWindow()
-	if ui.showOptionsWindow then
-		if not optionModalOpen then
-			ui.openPopup("Options")
```
Comment (Web-eWorks) [inline data/pigui/modules/settings-window.lua]: Thank you for cleaning up this style of code in particular! I'd much rather we call one function to open rather than have to check it every frame.

File: data/pigui/modules/station-view/01-lobby.lua [hunk 7]
```diff
@@ -49,7 +50,15 @@ local hydrogenIcon = PiImage.New("icons/goods/Hydrogen.png")
 local hyperdriveIcon = PiImage.New("icons/goods/Hydrogen.png")
 
 local popupMsg = ''
-local popupId = 'lobbyPopup'
+local popup
+popup = ModalWindow.New('lobbyPopup', function()
```
Comment (Web-eWorks) [inline data/pigui/modules/station-view/01-lobby.lua]: Same issue here, please prefer the `local popup = ModalWindow.New` style over split lines.

File: data/pigui/libs/modal-win.lua (hunk 1 above)
Comment (vakhoir) [reply data/pigui/libs/modal-win.lua]: Not exactly - it's not possible to do a recursive call if the function isn't already declared. The game crashes if you try to do it in a single line.

Comment (Web-eWorks) [reply data/pigui/libs/modal-win.lua]: That's weird, because the 5.2 manual explicitly states that here: https://www.lua.org/manual/5.2/manual.html#3.4.10

If it's crashing like that, there may be a deeper problem...

Comment (Web-eWorks) [reply data/pigui/libs/modal-win.lua]: Ah. I think I understand. Please prefer the use of `local function name()` rather than `local name = function()` - it's much easier to read and it gives more reliable results for Lua's debugger.

File: data/pigui/modules/station-view/01-lobby.lua (hunk 7 above)
Comment (vakhoir) [reply data/pigui/modules/station-view/01-lobby.lua]: `local function funcName()` worked for allowing a recursive call, but I'm not sure there's a way around it here. `popup` needs to be at least declared to be referenced inside the render function.

File: data/pigui/libs/modal-win.lua (hunk 3 above)
Comment (vakhoir) [reply data/pigui/libs/modal-win.lua]: I don't know what I was thinking :D

File: data/pigui/modules/saveloadgame.lua (hunk 4 above)
Comment (vakhoir) [reply data/pigui/modules/saveloadgame.lua]: I think that's still from the pre-modal save window days, I just didn't touch it when I made the window modal. Fixed now.

File: data/pigui/modules/saveloadgame.lua (hunk 5 above)
Comment (vakhoir) [reply data/pigui/modules/saveloadgame.lua]: I fixed the spacing, but now I'm wondering if the check shouldn't be changed to `selectedSave ~= nil and selectedSave ~= ''` like what is used in `closeAndLoadOrSave`

File: data/pigui/modules/settings-window.lua (hunk 6 above)
Comment (vakhoir) [reply data/pigui/modules/settings-window.lua]: Yeah, that was the part that was driving me up the wall with popups. It was very awkard to have to check both if the window should be rendered and if it was opened already.
It's a bit silly we have to keep track of the popup stack when ImGui is doing it too, but the code should be more manageable.

File: data/pigui/modules/saveloadgame.lua (hunk 5 above)
Comment (vakhoir) [reply data/pigui/modules/saveloadgame.lua]: I went ahead and added the `selectedSave ~= ''` check.

**Comment by vakhoir** [comment]
I applied all the changes. They're in a separate commit for ease of review, I'll squash them once there's a green light to merge.

File: data/pigui/libs/modal-win.lua [hunk 8]
```diff
@@ -7,22 +7,19 @@ local modals = {}
...
+		flags = flags or defaultModalFlags,
 		stackIdx = -1,
 		isOpen = false,
 		innerHandler = innerHandler,
-		outerHandler = outerHandler,
-	}
-
-	if not outerHandler then
-		self.outerHandler = function(drawPopupFn)
+		outerHandler = outerHandler or function(slf, drawPopupFn)
```
Comment (Web-eWorks) [inline data/pigui/libs/modal-win.lua]: This is the world's tiniest nitpick, but I'd recommend using `self` for consistency.
```suggestion
		outerHandler = outerHandler or function(self, drawPopupFn)
```

Comment (vakhoir) [reply data/pigui/libs/modal-win.lua]: Fixed and squashed

**Comment by vakhoir** [comment]
Fixed and squashed

File: data/pigui/libs/modal-win.lua (hunk 8 above)
Comment (vakhoir) [reply data/pigui/libs/modal-win.lua]: I also renamed the new instance variable to modalWin, it was the whole reason for naming the function argument "slf" - didn't want to confuse people.

**Comment by impaktor** [comment]
I assume this can be merged now? I'll merge in 24 hours, if this is still open, and no objections.

I think I'll need this for the Police-tab stuff I've been working on.

**Comment by Web-eWorks** [comment]
Sorry about the delay... I've been up to my neck in sandboxing and forgot to hit the shiny merge button!
