### PR TITLE
_import() rework and fix for #4124

### LINKED ISSUE #4124: Module instances are created twice
_(updated)_
Trying to create similar module with single table instance, but have that problem. Original module call and import() creates two different instances. Adding more files with more imports have no effect.
Know how to workaround, but it looks dirty (attach module to pigui and check each time).

Example: 
**data/pigui/modules/testModule.lua**
```Lua
local UI = import("pigui/pigui.lua")

local t = {}

function test()
	print("t: " .. tostring(t))
end

UI.registerModule("game", test)

return t
```

**data/pigui/modules/testModule2.lua**
```Lua
local testModule = import("testModule")
```

Output:
default

I think need to use import() here or anything like that, what use cache of import:
https://github.com/pioneerspacesim/pioneer/blob/86c29a430ba26f72b27ba5430f0e9fc3ed951b2f/src/Pi.cpp#L325

### PR DESCRIPTION
**Pull request by ColdSpirit0**
Now _import tries to load by name, tries to load with ".lua" extension, then tries
to load from import directories and then relative by caller directory (if it
exists) with and without extension.
Imported files saves in the cache with full path key to avoid
duplicates.
New import should to work little slower than old, but it more
intuitive and support more variations.

Fixes multiinstance trouble, In future better to use import instead a dofile.

@ecraven you can to add own directories like "pigui" to load with import("pigui") here:
https://github.com/ColdSpirit0/pioneer/blob/320b16f84017d233e526121467bff2b54a7662d8/src/LuaUtils.cpp#L291

fixes #4124

### CODE REVIEW

**Comment by ecraven** [comment]
@laarmen could you have a look at this?

**Comment by fluffyfreak** [comment]
Looks good to me, would be good to have a @laarmen or an @impaktor give it a once over but otherwise I'll merge it in a day or two.

**Comment by impaktor** [comment]
I waive my rights to review, and look at @laarmen or @ecraven

**Comment by ecraven** [comment]
Just build it, out of the box I get the following crash:
```
import: libs/autoload.lua not found
import: ui/FileDialog.lua not found
import: ui/GalacticView.lua not found
import: ui/InfoView.lua not found
Game::CanLoadGame('_exit')
import: ui/MainMenu.lua not found
import: ui/QuitConfirmation.lua not found
import: ui/Settings.lua not found
pioneer: lapi.c:679: lua_createtable: Assertion `(L->top <= L->ci->top) && "stack overflow"' failed.
```

**Comment by ecraven** [comment]
@ColdSpirit0: did you test this? It doesn't run for me at all, and it doesn't look as if this were a problem with my concrete setup.

**Comment by laarmen** [comment]
I'll try and have a look tonight. Perhaps.

**Comment by fluffyfreak** [comment]
Holding off merging whilst investigating Linux issue

**Comment by ecraven** [comment]
Stack trace with debugging.
Strange thing:
```
import [EquipSet]: trying to load from cache
import [EquipSet]: found cached libs/EquipSet.lua
import [EquipSet]: trying to load from cache
import [EquipSet]: found cached libs/EquipSet.lua
...
```
Full trace:
```
import [EquipSet]: trying to load from cache
import [EquipSet]: not cached
import [EquipSet]: trying to load file
import [utils]: called from libs
import [utils]: trying to load from cache
import [utils]: not cached
import [utils]: trying to load file
import [utils]: found and loaded file libs/utils.lua
import [utils]: entering into cache
import [Serializer]: called from libs
import [Serializer]: trying to load from cache
import [Serializer]: not cached
import [Serializer]: trying to load file
import [Serializer]: not found
import [Serializer]: trying core import
import [Serializer]: entering into cache
import [EquipSet]: found and loaded file libs/EquipSet.lua
import [EquipSet]: entering into cache
import [EquipSet]: trying to load from cache
import [EquipSet]: found cached libs/EquipSet.lua
import [EquipSet]: trying to load from cache
import [EquipSet]: found cached libs/EquipSet.lua
import [EquipSet]: trying to load from cache
import [EquipSet]: found cached libs/EquipSet.lua
import [EquipSet]: trying to load from cache
import [EquipSet]: found cached libs/EquipSet.lua
import [EquipSet]: trying to load from cache
import [EquipSet]: found cached libs/EquipSet.lua
import [EquipSet]: trying to load from cache
import [EquipSet]: found cached libs/EquipSet.lua
import [EquipSet]: trying to load from cache
import [EquipSet]: found cached libs/EquipSet.lua
import [EquipSet]: trying to load from cache
import [EquipSet]: found cached libs/EquipSet.lua
import [EquipSet]: trying to load from cache
import [EquipSet]: found cached libs/EquipSet.lua
import [EquipSet]: trying to load from cache
import [EquipSet]: found cached libs/EquipSet.lua
import [EquipSet]: trying to load from cache
import [EquipSet]: found cached libs/EquipSet.lua
import [EquipSet]: trying to load from cache
import [EquipSet]: found cached libs/EquipSet.lua
import [EquipSet]: trying to load from cache
import [EquipSet]: found cached libs/EquipSet.lua
import [EquipSet]: trying to load from cache
import [EquipSet]: found cached libs/EquipSet.lua
import [EquipSet]: trying to load from cache
import [EquipSet]: found cached libs/EquipSet.lua
import [EquipSet]: trying to load from cache
import [EquipSet]: found cached libs/EquipSet.lua
import [EquipSet]: trying to load from cache
import [EquipSet]: found cached libs/EquipSet.lua
import [EquipSet]: trying to load from cache
import [EquipSet]: found cached libs/EquipSet.lua
import [EquipSet]: trying to load from cache
import [EquipSet]: found cached libs/EquipSet.lua
import [EquipSet]: trying to load from cache
import [EquipSet]: found cached libs/EquipSet.lua
import [EquipSet]: trying to load from cache
import [EquipSet]: found cached libs/EquipSet.lua
import [EquipSet]: trying to load from cache
import [EquipSet]: found cached libs/EquipSet.lua
import [EquipSet]: trying to load from cache
import [EquipSet]: found cached libs/EquipSet.lua
import [EquipSet]: trying to load from cache
import [EquipSet]: found cached libs/EquipSet.lua
import [EquipSet]: trying to load from cache
import [EquipSet]: found cached libs/EquipSet.lua
import [EquipSet]: trying to load from cache
import [EquipSet]: found cached libs/EquipSet.lua
import [EquipSet]: trying to load from cache
import [EquipSet]: found cached libs/EquipSet.lua
import [libs/autoload.lua]: trying to load from cache
import [libs/autoload.lua]: not cached
import [libs/autoload.lua]: trying to load file
import [SpaceStation]: called from libs
import [SpaceStation]: trying to load from cache
import [SpaceStation]: not cached
import [SpaceStation]: trying to load file
import [Event]: called from libs
import [Event]: trying to load from cache
import [Event]: not cached
import [Event]: trying to load file
import [Engine]: called from libs
import [Engine]: trying to load from cache
import [Engine]: not cached
import [Engine]: trying to load file
import [Engine]: not found
import [Engine]: trying core import
import [Engine]: entering into cache
import [Event]: found and loaded file libs/Event.lua
import [Event]: entering into cache
import [Rand]: called from libs
import [Rand]: trying to load from cache
import [Rand]: not cached
import [Rand]: trying to load file
import [Rand]: not found
import [Rand]: trying core import
import [Rand]: entering into cache
import [Space]: called from libs
import [Space]: trying to load from cache
import [Space]: not cached
import [Space]: trying to load file
import [Space]: not found
import [Space]: trying core import
import [Space]: entering into cache
import [utils]: called from libs
import [utils]: trying to load from cache
import [utils]: found cached libs/utils.lua
import [ShipDef]: called from libs
import [ShipDef]: trying to load from cache
import [ShipDef]: not cached
import [ShipDef]: trying to load file
import [ShipDef]: not found
import [ShipDef]: trying core import
import [ShipDef]: entering into cache
import [Engine]: called from libs
import [Engine]: trying to load from cache
import [Engine]: found cached libs/Engine.lua
import [Timer]: called from libs
import [Timer]: trying to load from cache
import [Timer]: not cached
import [Timer]: trying to load file
import [Timer]: not found
import [Timer]: trying core import
import [Timer]: entering into cache
import [Game]: called from libs
import [Game]: trying to load from cache
import [Game]: not cached
import [Game]: trying to load file
import [Event]: called from libs
import [Event]: trying to load from cache
import [Event]: found cached libs/Event.lua
import [Game]: found and loaded file libs/Game.lua
import [Game]: entering into cache
import [Ship]: called from libs
import [Ship]: trying to load from cache
import [Ship]: not cached
import [Ship]: trying to load file
import [Engine]: called from libs
import [Engine]: trying to load from cache
import [Engine]: found cached libs/Engine.lua
import [Event]: called from libs
import [Event]: trying to load from cache
import [Event]: found cached libs/Event.lua
import [Serializer]: called from libs
import [Serializer]: trying to load from cache
import [Serializer]: found cached libs/Serializer.lua
import [ShipDef]: called from libs
import [ShipDef]: trying to load from cache
import [ShipDef]: found cached libs/ShipDef.lua
import [Equipment]: called from libs
import [Equipment]: trying to load from cache
import [Equipment]: not cached
import [Equipment]: trying to load file
import [utils]: called from libs
import [utils]: trying to load from cache
import [utils]: found cached libs/utils.lua
import [Serializer]: called from libs
import [Serializer]: trying to load from cache
import [Serializer]: found cached libs/Serializer.lua
import [Lang]: called from libs
import [Lang]: trying to load from cache
import [Lang]: not cached
import [Lang]: trying to load file
import [Lang]: not found
import [Lang]: trying core import
import [Lang]: entering into cache
import [ShipDef]: called from libs
import [ShipDef]: trying to load from cache
import [ShipDef]: found cached libs/ShipDef.lua
import [Timer]: called from libs
import [Timer]: trying to load from cache
import [Timer]: found cached libs/Timer.lua
import [Comms]: called from libs
import [Comms]: trying to load from cache
import [Comms]: not cached
import [Comms]: trying to load file
import [Comms]: not found
import [Comms]: trying core import
import [Comms]: entering into cache
import [Equipment]: found and loaded file libs/Equipment.lua
import [Equipment]: entering into cache
import [Timer]: called from libs
import [Timer]: trying to load from cache
import [Timer]: found cached libs/Timer.lua
import [Lang]: called from libs
import [Lang]: trying to load from cache
import [Lang]: found cached libs/Lang.lua
import [Character]: called from libs
import [Character]: trying to load from cache
import [Character]: not cached
import [Character]: trying to load file
import [Engine]: called from libs
import [Engine]: trying to load from cache
import [Engine]: found cached libs/Engine.lua
import [Game]: called from libs
import [Game]: trying to load from cache
import [Game]: found cached libs/Game.lua
import [Event]: called from libs
import [Event]: trying to load from cache
import [Event]: found cached libs/Event.lua
import [NameGen]: called from libs
import [NameGen]: trying to load from cache
import [NameGen]: not cached
import [NameGen]: trying to load file
import [Engine]: called from libs
import [Engine]: trying to load from cache
import [Engine]: found cached libs/Engine.lua
import [NameGen]: found and loaded file libs/NameGen.lua
import [NameGen]: entering into cache
import [Serializer]: called from libs
import [Serializer]: trying to load from cache
import [Serializer]: found cached libs/Serializer.lua
import [Character]: found and loaded file libs/Character.lua
import [Character]: entering into cache
import [Comms]: called from libs
import [Comms]: trying to load from cache
import [Comms]: found cached libs/Comms.lua
import [Ship]: found and loaded file libs/Ship.lua
import [Ship]: entering into cache
import [SceneGraph.Model]: called from libs
import [SceneGraph.Model]: trying to load from cache
import [SceneGraph.Model]: not cached
import [SceneGraph.Model]: trying to load file
import [SceneGraph.Model]: not found
import [SceneGraph.Model]: trying core import
import [SceneGraph.Model]: entering into cache
import [SceneGraph.ModelSkin]: called from libs
import [SceneGraph.ModelSkin]: trying to load from cache
import [SceneGraph.ModelSkin]: not cached
import [SceneGraph.ModelSkin]: trying to load file
import [SceneGraph.ModelSkin]: not found
import [SceneGraph.ModelSkin]: trying core import
import [SceneGraph.ModelSkin]: entering into cache
import [Serializer]: called from libs
import [Serializer]: trying to load from cache
import [Serializer]: found cached libs/Serializer.lua
import [Equipment]: called from libs
import [Equipment]: trying to load from cache
import [Equipment]: found cached libs/Equipment.lua
import [Faction]: called from libs
import [Faction]: trying to load from cache
import [Faction]: not cached
import [Faction]: trying to load file
import [Faction]: not found
import [Faction]: trying core import
import [Faction]: entering into cache
import [Lang]: called from libs
import [Lang]: trying to load from cache
import [Lang]: found cached libs/Lang.lua
import [SpaceStation]: found and loaded file libs/SpaceStation.lua
import [SpaceStation]: entering into cache
import [libs/autoload.lua]: found and loaded file libs/autoload.lua
import: libs/autoload.lua not found
import [ui/ErrorScreen.lua]: trying to load from cache
import [ui/ErrorScreen.lua]: not cached
import [ui/ErrorScreen.lua]: trying to load file
import [Engine]: called from ui
import [Engine]: trying to load from cache
import [Engine]: found cached libs/Engine.lua
import [Lang]: called from ui
import [Lang]: trying to load from cache
import [Lang]: found cached libs/Lang.lua
import [ui/ErrorScreen.lua]: found and loaded file ui/ErrorScreen.lua
import [ui/ErrorScreen.lua]: entering into cache
import [ui/FileDialog.lua]: trying to load from cache
import [ui/FileDialog.lua]: not cached
import [ui/FileDialog.lua]: trying to load file
import [Engine]: called from ui
import [Engine]: trying to load from cache
import [Engine]: found cached libs/Engine.lua
import [Lang]: called from ui
import [Lang]: trying to load from cache
import [Lang]: found cached libs/Lang.lua
import [FileSystem]: called from ui
import [FileSystem]: trying to load from cache
import [FileSystem]: not cached
import [FileSystem]: trying to load file
import [FileSystem]: not found
import [FileSystem]: trying core import
import [FileSystem]: entering into cache
import [Format]: called from ui
import [Format]: trying to load from cache
import [Format]: not cached
import [Format]: trying to load file
import [Format]: not found
import [Format]: trying core import
import [Format]: entering into cache
import [ui/FileDialog.lua]: found and loaded file ui/FileDialog.lua
import: ui/FileDialog.lua not found
import [ui/GalacticView.lua]: trying to load from cache
import [ui/GalacticView.lua]: not cached
import [ui/GalacticView.lua]: trying to load file
import [Engine]: called from ui
import [Engine]: trying to load from cache
import [Engine]: found cached libs/Engine.lua
import [Game]: called from ui
import [Game]: trying to load from cache
import [Game]: found cached libs/Game.lua
import [Lang]: called from ui
import [Lang]: trying to load from cache
import [Lang]: found cached libs/Lang.lua
import [UI.Game.GalaxyMap]: called from ui
import [UI.Game.GalaxyMap]: trying to load from cache
import [UI.Game.GalaxyMap]: not cached
import [UI.Game.GalaxyMap]: trying to load file
import [UI.Game.GalaxyMap]: not found
import [UI.Game.GalaxyMap]: trying core import
import [UI.Game.GalaxyMap]: entering into cache
import [ui/GalacticView.lua]: found and loaded file ui/GalacticView.lua
import: ui/GalacticView.lua not found
import [ui/InfoView/CrewRoster.lua]: trying to load from cache
import [ui/InfoView/CrewRoster.lua]: not cached
import [ui/InfoView/CrewRoster.lua]: trying to load file
import [Engine]: called from ui/InfoView
import [Engine]: trying to load from cache
import [Engine]: found cached libs/Engine.lua
import [Lang]: called from ui/InfoView
import [Lang]: trying to load from cache
import [Lang]: found cached libs/Lang.lua
import [Game]: called from ui/InfoView
import [Game]: trying to load from cache
import [Game]: found cached libs/Game.lua
import [Format]: called from ui/InfoView
import [Format]: trying to load from cache
import [Format]: not cached
import [Format]: trying to load file
import [Format]: not found
import [Format]: trying core import
import [Format]: entering into cache
import [ShipDef]: called from ui/InfoView
import [ShipDef]: trying to load from cache
import [ShipDef]: found cached libs/ShipDef.lua
import [Comms]: called from ui/InfoView
import [Comms]: trying to load from cache
import [Comms]: found cached libs/Comms.lua
import [Equipment]: called from ui/InfoView
import [Equipment]: trying to load from cache
import [Equipment]: found cached libs/Equipment.lua
import [ui/InfoFace]: called from ui/InfoView
import [ui/InfoFace]: trying to load from cache
import [ui/InfoFace]: not cached
import [ui/InfoFace]: trying to load file
import [Engine]: called from libs/ui
import [Engine]: trying to load from cache
import [Engine]: found cached libs/Engine.lua
import [UI.Game.Face]: called from libs/ui
import [UI.Game.Face]: trying to load from cache
import [UI.Game.Face]: not cached
import [UI.Game.Face]: trying to load file
import [UI.Game.Face]: not found
import [UI.Game.Face]: trying core import
import [UI.Game.Face]: entering into cache
import [ui/InfoFace]: found and loaded file libs/ui/InfoFace.lua
import [ui/InfoFace]: entering into cache
import [ui/SmallLabeledButton]: called from ui/InfoView
import [ui/SmallLabeledButton]: trying to load from cache
import [ui/SmallLabeledButton]: not cached
import [ui/SmallLabeledButton]: trying to load file
import [Engine]: called from libs/ui
import [Engine]: trying to load from cache
import [Engine]: found cached libs/Engine.lua
import [ui/SmallLabeledButton]: found and loaded file libs/ui/SmallLabeledButton.lua
import [ui/SmallLabeledButton]: entering into cache
import [ui/InfoView/CrewRoster.lua]: found and loaded file ui/InfoView/CrewRoster.lua
import [ui/InfoView/CrewRoster.lua]: entering into cache
import [ui/InfoView/EconTrade.lua]: trying to load from cache
import [ui/InfoView/EconTrade.lua]: not cached
import [ui/InfoView/EconTrade.lua]: trying to load file
import [Engine]: called from ui/InfoView
import [Engine]: trying to load from cache
import [Engine]: found cached libs/Engine.lua
import [Lang]: called from ui/InfoView
import [Lang]: trying to load from cache
import [Lang]: found cached libs/Lang.lua
import [Game]: called from ui/InfoView
import [Game]: trying to load from cache
import [Game]: found cached libs/Game.lua
import [Equipment]: called from ui/InfoView
import [Equipment]: trying to load from cache
import [Equipment]: found cached libs/Equipment.lua
import [ShipDef]: called from ui/InfoView
import [ShipDef]: trying to load from cache
import [ShipDef]: found cached libs/ShipDef.lua
import [ui/SmallLabeledButton]: called from ui/InfoView
import [ui/SmallLabeledButton]: trying to load from cache
import [ui/SmallLabeledButton]: found cached libs/ui/SmallLabeledButton.lua
import [ui/InfoGauge]: called from ui/InfoView
import [ui/InfoGauge]: trying to load from cache
import [ui/InfoGauge]: not cached
import [ui/InfoGauge]: trying to load file
import [Engine]: called from libs/ui
import [Engine]: trying to load from cache
import [Engine]: found cached libs/Engine.lua
import [ui/InfoGauge]: found and loaded file libs/ui/InfoGauge.lua
import [ui/InfoGauge]: entering into cache
import [ui/InfoView/EconTrade.lua]: found and loaded file ui/InfoView/EconTrade.lua
import [ui/InfoView/EconTrade.lua]: entering into cache
import [ui/InfoView/Missions.lua]: trying to load from cache
import [ui/InfoView/Missions.lua]: not cached
import [ui/InfoView/Missions.lua]: trying to load file
import [Engine]: called from ui/InfoView
import [Engine]: trying to load from cache
import [Engine]: found cached libs/Engine.lua
import [Lang]: called from ui/InfoView
import [Lang]: trying to load from cache
import [Lang]: found cached libs/Lang.lua
import [Game]: called from ui/InfoView
import [Game]: trying to load from cache
import [Game]: found cached libs/Game.lua
import [Format]: called from ui/InfoView
import [Format]: trying to load from cache
import [Format]: found cached ui/InfoView/Format.lua
import [Character]: called from ui/InfoView
import [Character]: trying to load from cache
import [Character]: found cached libs/Character.lua
import [ui/SmallLabeledButton]: called from ui/InfoView
import [ui/SmallLabeledButton]: trying to load from cache
import [ui/SmallLabeledButton]: found cached libs/ui/SmallLabeledButton.lua
import [ui/SmartTable]: called from ui/InfoView
import [ui/SmartTable]: trying to load from cache
import [ui/SmartTable]: not cached
import [ui/SmartTable]: trying to load file
import [Engine]: called from libs/ui
import [Engine]: trying to load from cache
import [Engine]: found cached libs/Engine.lua
import [utils]: called from libs/ui
import [utils]: trying to load from cache
import [utils]: found cached libs/utils.lua
import [ui/SmartTable]: found and loaded file libs/ui/SmartTable.lua
import [ui/SmartTable]: entering into cache
import [ui/InfoView/Missions.lua]: found and loaded file ui/InfoView/Missions.lua
import [ui/InfoView/Missions.lua]: entering into cache
import [ui/InfoView/OrbitalAnalysis.lua]: trying to load from cache
import [ui/InfoView/OrbitalAnalysis.lua]: not cached
import [ui/InfoView/OrbitalAnalysis.lua]: trying to load file
import [Engine]: called from ui/InfoView
import [Engine]: trying to load from cache
import [Engine]: found cached libs/Engine.lua
import [Lang]: called from ui/InfoView
import [Lang]: trying to load from cache
import [Lang]: found cached libs/Lang.lua
import [Game]: called from ui/InfoView
import [Game]: trying to load from cache
import [Game]: found cached libs/Game.lua
import [Space]: called from ui/InfoView
import [Space]: trying to load from cache
import [Space]: found cached libs/Space.lua
import [ui/InfoView/OrbitalAnalysis.lua]: found and loaded file ui/InfoView/OrbitalAnalysis.lua
import [ui/InfoView/OrbitalAnalysis.lua]: entering into cache
import [ui/InfoView/PersonalInfo.lua]: trying to load from cache
import [ui/InfoView/PersonalInfo.lua]: not cached
import [ui/InfoView/PersonalInfo.lua]: trying to load file
import [Engine]: called from ui/InfoView
import [Engine]: trying to load from cache
import [Engine]: found cached libs/Engine.lua
import [Lang]: called from ui/InfoView
import [Lang]: trying to load from cache
import [Lang]: found cached libs/Lang.lua
import [Character]: called from ui/InfoView
import [Character]: trying to load from cache
import [Character]: found cached libs/Character.lua
import [ui/InfoFace]: called from ui/InfoView
import [ui/InfoFace]: trying to load from cache
import [ui/InfoFace]: found cached libs/ui/InfoFace.lua
import [ui/SmallLabeledButton]: called from ui/InfoView
import [ui/SmallLabeledButton]: trying to load from cache
import [ui/SmallLabeledButton]: found cached libs/ui/SmallLabeledButton.lua
import [ui/InfoView/PersonalInfo.lua]: found and loaded file ui/InfoView/PersonalInfo.lua
import [ui/InfoView/PersonalInfo.lua]: entering into cache
import [ui/InfoView/ShipInfo.lua]: trying to load from cache
import [ui/InfoView/ShipInfo.lua]: not cached
import [ui/InfoView/ShipInfo.lua]: trying to load file
import [Engine]: called from ui/InfoView
import [Engine]: trying to load from cache
import [Engine]: found cached libs/Engine.lua
import [Lang]: called from ui/InfoView
import [Lang]: trying to load from cache
import [Lang]: found cached libs/Lang.lua
import [Game]: called from ui/InfoView
import [Game]: trying to load from cache
import [Game]: found cached libs/Game.lua
import [Equipment]: called from ui/InfoView
import [Equipment]: trying to load from cache
import [Equipment]: found cached libs/Equipment.lua
import [ShipDef]: called from ui/InfoView
import [ShipDef]: trying to load from cache
import [ShipDef]: found cached libs/ShipDef.lua
import [UI.Game.ModelSpinner]: called from ui/InfoView
import [UI.Game.ModelSpinner]: trying to load from cache
import [UI.Game.ModelSpinner]: not cached
import [UI.Game.ModelSpinner]: trying to load file
import [UI.Game.ModelSpinner]: not found
import [UI.Game.ModelSpinner]: trying core import
import [UI.Game.ModelSpinner]: entering into cache
import [ui/InfoView/ShipInfo.lua]: found and loaded file ui/InfoView/ShipInfo.lua
import [ui/InfoView/ShipInfo.lua]: entering into cache
import [ui/InfoView.lua]: trying to load from cache
import [ui/InfoView.lua]: not cached
import [ui/InfoView.lua]: trying to load file
import [Engine]: called from ui
import [Engine]: trying to load from cache
import [Engine]: found cached libs/Engine.lua
import [Lang]: called from ui
import [Lang]: trying to load from cache
import [Lang]: found cached libs/Lang.lua
import [Event]: called from ui
import [Event]: trying to load from cache
import [Event]: found cached libs/Event.lua
import [ui/TabView]: called from ui
import [ui/TabView]: trying to load from cache
import [ui/TabView]: not cached
import [ui/TabView]: trying to load file
import [Engine]: called from libs/ui
import [Engine]: trying to load from cache
import [Engine]: found cached libs/Engine.lua
import [ui/TabView]: found and loaded file libs/ui/TabView.lua
import [ui/TabView]: entering into cache
import [InfoView/ShipInfo]: called from ui
import [InfoView/ShipInfo]: trying to load from cache
import [InfoView/ShipInfo]: found cached ui/InfoView/ShipInfo.lua
import [InfoView/PersonalInfo]: called from ui
import [InfoView/PersonalInfo]: trying to load from cache
import [InfoView/PersonalInfo]: found cached ui/InfoView/PersonalInfo.lua
import [InfoView/EconTrade]: called from ui
import [InfoView/EconTrade]: trying to load from cache
import [InfoView/EconTrade]: found cached ui/InfoView/EconTrade.lua
import [InfoView/Missions]: called from ui
import [InfoView/Missions]: trying to load from cache
import [InfoView/Missions]: found cached ui/InfoView/Missions.lua
import [InfoView/CrewRoster]: called from ui
import [InfoView/CrewRoster]: trying to load from cache
import [InfoView/CrewRoster]: found cached ui/InfoView/CrewRoster.lua
import [InfoView/OrbitalAnalysis]: called from ui
import [InfoView/OrbitalAnalysis]: trying to load from cache
import [InfoView/OrbitalAnalysis]: found cached ui/InfoView/OrbitalAnalysis.lua
import [ui/InfoView.lua]: found and loaded file ui/InfoView.lua
import: ui/InfoView.lua not found
import [ui/MainMenu.lua]: trying to load from cache
import [ui/MainMenu.lua]: not cached
import [ui/MainMenu.lua]: trying to load file
import [Engine]: called from ui
import [Engine]: trying to load from cache
import [Engine]: found cached libs/Engine.lua
import [Lang]: called from ui
import [Lang]: trying to load from cache
import [Lang]: found cached libs/Lang.lua
import [Game]: called from ui
import [Game]: trying to load from cache
import [Game]: found cached libs/Game.lua
import [Ship]: called from ui
import [Ship]: trying to load from cache
import [Ship]: found cached libs/Ship.lua
import [ShipDef]: called from ui
import [ShipDef]: trying to load from cache
import [ShipDef]: found cached libs/ShipDef.lua
import [Player]: called from ui
import [Player]: trying to load from cache
import [Player]: not cached
import [Player]: trying to load file
import [Serializer]: called from libs
import [Serializer]: trying to load from cache
import [Serializer]: found cached libs/Serializer.lua
import [Event]: called from libs
import [Event]: trying to load from cache
import [Event]: found cached libs/Event.lua
import [Game]: called from libs
import [Game]: trying to load from cache
import [Game]: found cached libs/Game.lua
import [utils]: called from libs
import [utils]: trying to load from cache
import [utils]: found cached libs/utils.lua
import [Legal]: called from libs
import [Legal]: trying to load from cache
import [Legal]: not cached
import [Legal]: trying to load file
import [Comms]: called from libs
import [Comms]: trying to load from cache
import [Comms]: found cached libs/Comms.lua
import [Game]: called from libs
import [Game]: trying to load from cache
import [Game]: found cached libs/Game.lua
import [Lang]: called from libs
import [Lang]: trying to load from cache
import [Lang]: found cached libs/Lang.lua
import [Legal]: found and loaded file libs/Legal.lua
import [Legal]: entering into cache
import [Player]: found and loaded file libs/Player.lua
import [Player]: entering into cache
import [SystemPath]: called from ui
import [SystemPath]: trying to load from cache
import [SystemPath]: not cached
import [SystemPath]: trying to load file
import [SystemPath]: not found
import [SystemPath]: trying core import
import [SystemPath]: entering into cache
import [ErrorScreen]: called from ui
import [ErrorScreen]: trying to load from cache
import [ErrorScreen]: found cached ui/ErrorScreen.lua
import [Equipment]: called from ui
import [Equipment]: trying to load from cache
import [Equipment]: found cached libs/Equipment.lua
Game::CanLoadGame('_exit')
import [ui/MainMenu.lua]: found and loaded file ui/MainMenu.lua
import: ui/MainMenu.lua not found
import [ui/QuitConfirmation.lua]: trying to load from cache
import [ui/QuitConfirmation.lua]: not cached
import [ui/QuitConfirmation.lua]: trying to load file
import [Engine]: called from ui
import [Engine]: trying to load from cache
import [Engine]: found cached libs/Engine.lua
import [Lang]: called from ui
import [Lang]: trying to load from cache
import [Lang]: found cached libs/Lang.lua
import [ui/QuitConfirmation.lua]: found and loaded file ui/QuitConfirmation.lua
import: ui/QuitConfirmation.lua not found
import [ui/Settings.lua]: trying to load from cache
import [ui/Settings.lua]: not cached
import [ui/Settings.lua]: trying to load file
import [Game]: called from ui
import [Game]: trying to load from cache
import [Game]: found cached libs/Game.lua
import [Engine]: called from ui
import [Engine]: trying to load from cache
import [Engine]: found cached libs/Engine.lua
import [Lang]: called from ui
import [Lang]: trying to load from cache
import [Lang]: found cached libs/Lang.lua
import [utils]: called from ui
import [utils]: trying to load from cache
import [utils]: found cached libs/utils.lua
import [ui/TabView]: called from ui
import [ui/TabView]: trying to load from cache
import [ui/TabView]: found cached libs/ui/TabView.lua
import [ui/SmallLabeledButton]: called from ui
import [ui/SmallLabeledButton]: trying to load from cache
import [ui/SmallLabeledButton]: found cached libs/ui/SmallLabeledButton.lua
import [UI.Game.KeyBindingCapture]: called from ui
import [UI.Game.KeyBindingCapture]: trying to load from cache
import [UI.Game.KeyBindingCapture]: not cached
import [UI.Game.KeyBindingCapture]: trying to load file
import [UI.Game.KeyBindingCapture]: not found
import [UI.Game.KeyBindingCapture]: trying core import
import [UI.Game.KeyBindingCapture]: entering into cache
import [UI.Game.AxisBindingCapture]: called from ui
import [UI.Game.AxisBindingCapture]: trying to load from cache
import [UI.Game.AxisBindingCapture]: not cached
import [UI.Game.AxisBindingCapture]: trying to load file
import [UI.Game.AxisBindingCapture]: not found
import [UI.Game.AxisBindingCapture]: trying core import
import [UI.Game.AxisBindingCapture]: entering into cache
import [ErrorScreen]: called from ui
import [ErrorScreen]: trying to load from cache
import [ErrorScreen]: found cached ui/ErrorScreen.lua
import [ui/Settings.lua]: found and loaded file ui/Settings.lua
import: ui/Settings.lua not found
import [ui/StationView/BulletinBoard.lua]: trying to load from cache
import [ui/StationView/BulletinBoard.lua]: not cached
import [ui/StationView/BulletinBoard.lua]: trying to load file
import [Engine]: called from ui/StationView
import [Engine]: trying to load from cache
import [Engine]: found cached libs/Engine.lua
import [Game]: called from ui/StationView
import [Game]: trying to load from cache
import [Game]: found cached libs/Game.lua
import [SpaceStation]: called from ui/StationView
import [SpaceStation]: trying to load from cache
import [SpaceStation]: found cached libs/SpaceStation.lua
import [Event]: called from ui/StationView
import [Event]: trying to load from cache
import [Event]: found cached libs/Event.lua
import [ChatForm]: called from ui/StationView
import [ChatForm]: trying to load from cache
import [ChatForm]: not cached
import [ChatForm]: trying to load file
import [Engine]: called from ui/StationView
import [Engine]: trying to load from cache
import [Engine]: found cached libs/Engine.lua
import [Lang]: called from ui/StationView
import [Lang]: trying to load from cache
import [Lang]: found cached libs/Lang.lua
import [UI.Game.Face]: called from ui/StationView
import [UI.Game.Face]: trying to load from cache
import [UI.Game.Face]: not cached
import [UI.Game.Face]: trying to load file
import [UI.Game.Face]: not found
import [UI.Game.Face]: trying core import
import [UI.Game.Face]: entering into cache
import [ui/SmallLabeledButton]: called from ui/StationView
import [ui/SmallLabeledButton]: trying to load from cache
import [ui/SmallLabeledButton]: found cached libs/ui/SmallLabeledButton.lua
import [ui/NavButton]: called from ui/StationView
import [ui/NavButton]: trying to load from cache
import [ui/NavButton]: not cached
import [ui/NavButton]: trying to load file
import [Engine]: called from libs/ui
import [Engine]: trying to load from cache
import [Engine]: found cached libs/Engine.lua
import [Game]: called from libs/ui
import [Game]: trying to load from cache
import [Game]: found cached libs/Game.lua
import [Space]: called from libs/ui
import [Space]: trying to load from cache
import [Space]: found cached libs/Space.lua
import [ui/NavButton]: found and loaded file libs/ui/NavButton.lua
import [ui/NavButton]: entering into cache
import [EquipmentTableWidgets]: called from ui/StationView
import [EquipmentTableWidgets]: trying to load from cache
import [EquipmentTableWidgets]: not cached
import [EquipmentTableWidgets]: trying to load file
import [Engine]: called from ui/StationView
import [Engine]: trying to load from cache
import [Engine]: found cached libs/Engine.lua
import [Lang]: called from ui/StationView
import [Lang]: trying to load from cache
import [Lang]: found cached libs/Lang.lua
import [Game]: called from ui/StationView
import [Game]: trying to load from cache
import [Game]: found cached libs/Game.lua
import [utils]: called from ui/StationView
import [utils]: trying to load from cache
import [utils]: found cached libs/utils.lua
import [Format]: called from ui/StationView
import [Format]: trying to load from cache
import [Format]: not cached
import [Format]: trying to load file
import [Format]: not found
import [Format]: trying core import
import [Format]: entering into cache
import [Equipment]: called from ui/StationView
import [Equipment]: trying to load from cache
import [Equipment]: found cached libs/Equipment.lua
import [ui/MessageBox]: called from ui/StationView
import [ui/MessageBox]: trying to load from cache
import [ui/MessageBox]: not cached
import [ui/MessageBox]: trying to load file
import [Engine]: called from libs/ui
import [Engine]: trying to load from cache
import [Engine]: found cached libs/Engine.lua
import [ui/MessageBox]: found and loaded file libs/ui/MessageBox.lua
import [ui/MessageBox]: entering into cache
import [EquipmentTableWidgets]: found and loaded file ui/StationView/EquipmentTableWidgets.lua
import [EquipmentTableWidgets]: entering into cache
import [ChatForm]: found and loaded file ui/StationView/ChatForm.lua
import [ChatForm]: entering into cache
import [Lang]: called from ui/StationView
import [Lang]: trying to load from cache
import [Lang]: found cached libs/Lang.lua
import [ui/StationView/BulletinBoard.lua]: found and loaded file ui/StationView/BulletinBoard.lua
import [ui/StationView/BulletinBoard.lua]: entering into cache
import [ui/StationView/ChatForm.lua]: trying to load from cache
import [ui/StationView/ChatForm.lua]: found cached ui/StationView/ChatForm.lua
import [ui/StationView/CommodityMarket.lua]: trying to load from cache
import [ui/StationView/CommodityMarket.lua]: not cached
import [ui/StationView/CommodityMarket.lua]: trying to load file
import [Engine]: called from ui/StationView
import [Engine]: trying to load from cache
import [Engine]: found cached libs/Engine.lua
import [Lang]: called from ui/StationView
import [Lang]: trying to load from cache
import [Lang]: found cached libs/Lang.lua
import [Game]: called from ui/StationView
import [Game]: trying to load from cache
import [Game]: found cached libs/Game.lua
import [Format]: called from ui/StationView
import [Format]: trying to load from cache
import [Format]: found cached ui/StationView/Format.lua
import [Equipment]: called from ui/StationView
import [Equipment]: trying to load from cache
import [Equipment]: found cached libs/Equipment.lua
import [EquipmentTableWidgets]: called from ui/StationView
import [EquipmentTableWidgets]: trying to load from cache
import [EquipmentTableWidgets]: found cached ui/StationView/EquipmentTableWidgets.lua
import [ui/StationView/CommodityMarket.lua]: found and loaded file ui/StationView/CommodityMarket.lua
import [ui/StationView/CommodityMarket.lua]: entering into cache
import [ui/StationView/EquipmentMarket.lua]: trying to load from cache
import [ui/StationView/EquipmentMarket.lua]: not cached
import [ui/StationView/EquipmentMarket.lua]: trying to load file
import [Engine]: called from ui/StationView
import [Engine]: trying to load from cache
import [Engine]: found cached libs/Engine.lua
import [Lang]: called from ui/StationView
import [Lang]: trying to load from cache
import [Lang]: found cached libs/Lang.lua
import [Game]: called from ui/StationView
import [Game]: trying to load from cache
import [Game]: found cached libs/Game.lua
import [Format]: called from ui/StationView
import [Format]: trying to load from cache
import [Format]: found cached ui/StationView/Format.lua
import [EquipmentTableWidgets]: called from ui/StationView
import [EquipmentTableWidgets]: trying to load from cache
import [EquipmentTableWidgets]: found cached ui/StationView/EquipmentTableWidgets.lua
import [ui/StationView/EquipmentMarket.lua]: found and loaded file ui/StationView/EquipmentMarket.lua
import [ui/StationView/EquipmentMarket.lua]: entering into cache
import [ui/StationView/EquipmentTableWidgets.lua]: trying to load from cache
import [ui/StationView/EquipmentTableWidgets.lua]: found cached ui/StationView/EquipmentTableWidgets.lua
import [ui/StationView/Lobby.lua]: trying to load from cache
import [ui/StationView/Lobby.lua]: not cached
import [ui/StationView/Lobby.lua]: trying to load file
pioneer: lapi.c:679: lua_createtable: Assertion `(L->top <= L->ci->top) && "stack overflow"' failed.
```

**Comment by ColdSpirit0** [comment]
@ecraven sure I tested it) Now I will check it again

File: src/LuaUtils.cpp [hunk 1]
```diff
@@ -176,122 +176,261 @@ static bool _import_core(lua_State *L, const std::string &importName)
...
+	// if file exists
+	if (fileData)
+	{
+		pi_lua_dofile(L, *fileData, 1);
+		loaded = true;
+	}
 
-			if (ar.source[start] != '@' && end > 5)
-				start = 4;
+	LUA_DEBUG_END(L, 0);
```
Comment (laarmen) [inline src/LuaUtils.cpp]: Two questions:
1/ Why the need for the loaded flag when you can just return a test on fileData ?
2/ Reading the function description, this stack check should be LUA_DEBUG_END(L, fileData?1:0)

Comment (ColdSpirit0) [reply src/LuaUtils.cpp]: 1. It also doing dofile(). Just simple structure of code to read. I can to edit this if one bool costs to much =)
2. Dont know enough LUA_DEBUG, im just copied that from existing code. In the next commit I will try to edit that.

File: src/LuaUtils.cpp [hunk 2]
```diff
@@ -176,122 +176,261 @@ static bool _import_core(lua_State *L, const std::string &importName)
...
+
+		// load cache
+		lua_getfield(L, LUA_REGISTRYINDEX, "Imports");
+		assert(lua_istable(L, -1));
 
-				code = FileSystem::gameDataFiles.ReadFile(cacheName);
+		// check original name, with lua extension and relative by dirs by same rule
+		// if assumptions disabled, loop pass once and check only original importName
+		std::string cacheName;
+		for (int i = 0; i < (importDirectories.size() * !isFullName + 1); i++)
```
Comment (laarmen) [inline src/LuaUtils.cpp]: While the _import function is far too long as is, I'm pretty sure I'd rather have a more explicit way of expressing the boundary check here. Also, using a boolean operation result directly in an arithmetic expression is really not a good idea in my book.
```cpp
size_t dirsToCheck = 1;
if (!isFullName)
    dirsToCheck += importDirectories.size();
for (int i = 0; i < dirsToCheck; ++i)
```

File: src/LuaUtils.cpp [hunk 3]
```diff
@@ -176,122 +176,261 @@ static bool _import_core(lua_State *L, const std::string &importName)
...
+	else
+	{
+		// remove found "nil" from stack
+		lua_pop(L, 1);
 	}
-	lua_pop(L, 1);
-	DEBUG_PRINTF("import: not cached %s\n", cacheName.c_str());
 
-	RefCountedPtr<FileSystem::FileData> code = FileSystem::gameDataFiles.ReadFile(cacheName);
+	LUA_DEBUG_END(L, 0);
```
Comment (laarmen) [inline src/LuaUtils.cpp]: LUA_DEBUG_END(L, (found?1:0);

File: src/LuaUtils.cpp (hunk 2 above)
Comment (ColdSpirit0) [reply src/LuaUtils.cpp]: Agreed, I will change it

**Comment by ColdSpirit0** [comment]
@laarmen thanks for review) Is I should to apply `LUA_DEBUG_END` more often, for stack checking?
Then, I think, better to split _import to functions and write LUA_DEBUG in each one:
`
import_from_cache()
import_from_file()
import_base() : already exists
save_to_cache()
`

**Comment by laarmen** [comment]
Yes, LUA_DEBUG_END(l, x) checks the difference of stack size to the previous LUA_DEBUG_START. If it's different than x, the game will crash. As I said, I'm not sure the checks are enabled when compiling on Windows.

The proposed split sounds like the right idea :-)

**Comment by ColdSpirit0** [comment]
My previous commit should not work on windows... It was definitely a stack overflow... but it works %)

New comment here: [Fixed lua stack overflow, added indentedOutput](https://github.com/pioneerspacesim/pioneer/pull/4134/commits/135358feb8aafc24012b5537558d8a24b6955555)
At this time I carefully checked all stack changes, and tested game on Linux and Windows. I hope it will be work like a clock. Also I made IndentedOutput: when DEBUG_IMPORT is defined, output looks pretty. It can be useful in the other modules too.

I created a log with command `src/pioneer 2>pioneer.log`, started game on Earth and closed game after that.  When I read the log, I saw many (unuseful?) calls of import. To count relative amount of calls I used command:
``` sh
# command not count calls of import, but count occurences of that module in the log
# real count of calls in 2-6 smaller than in output
grep -Po '(?<=\[).*(?=\])' pioneer.log | sort | uniq -c | sort -nr > parsed.log
```

I put here top ten of the list:
```
  24307 NameGen
   1035 Event
    402 Engine
    354 Lang
    331 EquipSet
    223 Game
    144 Serializer
    138 Format
    120 ShipDef
    120 Comms
```
NameGen looks very popular =) 
Dont know what functions requires it, but I think it should be moderated. Should I to create a new issue?

I added pioneer.log and parsed.log to dropbox, also I made a custom style for vim to watch pioneer.log, you can see it all here: [importfix](https://www.dropbox.com/sh/t7aoly2123tmy42/AABVwQh0aNRdab3n5h56fGhFa?dl=0)

**Comment by ColdSpirit0** [comment]
I got all callers of NameGen and count it:
```sh
grep -Po '(?<=\[NameGen\]: import started, caller: ).*(?=$)' pioneer.log | sort | uniq -c | sort -nr
```

output:
```
   4529 core
    954 modules/Taxi/Taxi.lua
    421 modules/Assassination/Assassination.lua
    169 modules/TradeShips.lua
      1 modules/GoodsTrader/GoodsTrader.lua
      1 modules/BreakdownServicing/BreakdownServicing.lua
      1 libs/Character.lua
```
Core means somewhere in C++ code. Now output shows exact count of `import("NameGen")` calls.

**Comment by ColdSpirit0** [comment]
@laarmen please check my commit, it ready.

**Comment by impaktor** [comment]
@laarmen do you have time to see if you're happy with the changes @ColdSpirit0 did, based on your review?

**Comment by laarmen** [comment]
I shall take a look when I get back in about 2h.

**Comment by laarmen** [comment]
Well, I shan't. My brains are fried.

File: src/LuaUtils.cpp [hunk 4]
```diff
@@ -171,127 +171,363 @@ static bool _import_core(lua_State *L, const std::string &importName)
...
+		if (ar.source[start] != '@' && end > 5)
+			start = 4;
+
+		if (ar.source[start] == '@') {
+			start++;
+
+			static char source[1024];
+			strncpy(source, &ar.source[start], end - start + 1);
+
+			caller = std::string(source);
```
Comment (laarmen) [inline src/LuaUtils.cpp]: Why copy the string into an array if it's to wrap it in a std::string afterwards ? Couldn't you simply do
```cpp
caller = std::string(ar.source + start, end - start +1); // the +1 needs to be checked against the exact spec of std::string(char* src, size_t len);
```

File: src/LuaUtils.cpp [hunk 5]
```diff
@@ -171,127 +171,363 @@ static bool _import_core(lua_State *L, const std::string &importName)
...
 
-	// get the cache of previously imported things
-	lua_getfield(L, LUA_REGISTRYINDEX, "Imports");
+	// if have stack and caller in the stack
+	if (lua_getstack(L, 1, &ar) && lua_getinfo(L, "S", &ar) && ar.source)
+	{
+		int start = 0;
+		int end = strlen(ar.source);
+
+		if (ar.source[start] != '@' && end > 5)
```
Comment (laarmen) [inline src/LuaUtils.cpp]: Please add a comment regarding the nature of the prefix you're removing here?
Also, I'd be more comfortable with braces around the start=4; block.

File: src/LuaUtils.cpp [hunk 6]
```diff
@@ -171,127 +171,363 @@ static bool _import_core(lua_State *L, const std::string &importName)
...
+/**
+* Finds field in the cache.
+* Require a existing cache table in the stack at index -1.
+* Returns true if field not nil (exists), puts value to lua stack.
+*/
+static bool import_from_cache(lua_State *L, const ImportInfo& importInfo)
+{
+	LUA_DEBUG_START(L);
+	assert(lua_istable(L, -1));
+	DEBUG_INDENTED_PRINTF("import [%s]: trying to load from cache...", importInfo.importName.c_str());
```
Comment (laarmen) [inline src/LuaUtils.cpp]: Don't we have our own variant of printf that understands std::string? (I actually can't remember)

File: src/LuaUtils.cpp [hunk 7]
```diff
@@ -171,127 +171,363 @@ static bool _import_core(lua_State *L, const std::string &importName)
...
+
+/**
+* Tries to load file.
+* Returns true if file exists and puts return of dofile to stack.
+*/
+static bool load_file(lua_State *L, const std::string& name)
+{
+	LUA_DEBUG_START(L);
+
+	bool loaded = false;
```
Comment (laarmen) [inline src/LuaUtils.cpp]: Loaded is useless here, you can just check if ```fileData != null```

File: src/LuaUtils.cpp [hunk 8]
```diff
@@ -171,127 +171,363 @@ static bool _import_core(lua_State *L, const std::string &importName)
...
-				}
-				lua_pop(L, 1);
-				DEBUG_PRINTF("import: not cached %s\n", cacheName.c_str());
-
-				code = FileSystem::gameDataFiles.ReadFile(cacheName);
-			}
+/**
+* Tries to load file.
+* If file found returns true, puts return of dofile to stack, no matter nil it or value.
+* If import was successful, changes fileName in the importInfo to the filename that was found.
```
Comment (laarmen) [inline src/LuaUtils.cpp]: Hum. The doc says it changes something in the importInfo struct while the function signature uses a const ref. Which is it?

File: src/LuaUtils.cpp (hunk 5 above)
Comment (ColdSpirit0) [reply src/LuaUtils.cpp]: @laarmen sorry but it isnt my block of code, I just moved it from old import to separate function. Dont know for sure how it works. If need I can to understand the code and change somehow; please tell.

File: src/LuaUtils.cpp (hunk 6 above)
Comment (ColdSpirit0) [reply src/LuaUtils.cpp]: @laarmen no, all output functions receives char*. I think it work for other PR =)

File: src/LuaUtils.cpp (hunk 7 above)
Comment (ColdSpirit0) [reply src/LuaUtils.cpp]: @laarmen it is needed for that line:
~~~cpp
LUA_DEBUG_END(L, (loaded ? 1 : 0));
~~~

File: src/LuaUtils.cpp (hunk 8 above)
Comment (ColdSpirit0) [reply src/LuaUtils.cpp]: @laarmen it means I cant change importInfo object in full, but can change values. I thought about it early and decided to make consts in the struct:
~~~cpp
// simple struct to pass data between functions
struct ImportInfo
{
	const std::string& importName; // original name argument from "import(importName)"
	std::string& fileName; // name of the existing file
	const bool& isFullName; // if true import will no try to load relative to the importDirectories
	std::vector<std::string>& importDirectories; // contans list of paths where file can be imported
};
~~~
Maybe it should be changed, but I dont know how to make it elegant.

Comment (laarmen) [reply src/LuaUtils.cpp]: I don't like, and I'm actually surprised it compiles.
Please drop the const qualifier for the ref, it is IMO misleading.

File: src/LuaUtils.cpp (hunk 7 above)
Comment (laarmen) [reply src/LuaUtils.cpp]: LUA_DEBUG_END(L, (fileData ? 1 : 0)); works too.

File: src/LuaUtils.cpp (hunk 6 above)
Comment (laarmen) [reply src/LuaUtils.cpp]: ok

File: src/LuaUtils.cpp (hunk 5 above)
Comment (laarmen) [reply src/LuaUtils.cpp]: Fair enough. Could you please drop a comment with a TODO or XXX marker on it? Like XXX: Extraneous copy ?
TIA.

**Comment by ColdSpirit0** [comment]
@laarmen I did these changes, please check.

**Comment by laarmen** [comment]
I don't really have the time to go through the diff and discussion, and the last requested changes were really minor so if you think you've addressed them, that's good enough for me ;-).

OPEN THE MERGE GATES!

**Comment by impaktor** [comment]
We/I'll merge after speaking to @ColdSpirit0.

**Comment by ColdSpirit0** [comment]
@laarmen thank you for your time)
